# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class Account(Model):
    """Account.

    :param id: The id property for the account entity
    :type id: str
    :param number: The number property for the account entity
    :type number: str
    :param display_name: The displayName property for the account entity
    :type display_name: str
    :param category: The category property for the account entity
    :type category: str
    :param sub_category: The subCategory property for the account entity
    :type sub_category: str
    :param blocked: The blocked property for the account entity
    :type blocked: bool
    :param last_modified_date_time: The lastModifiedDateTime property for the
     account entity
    :type last_modified_date_time: datetime
    """

    _validation = {
        'number': {'max_length': 20},
        'display_name': {'max_length': 100},
        'sub_category': {'max_length': 80},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'number': {'key': 'number', 'type': 'str'},
        'display_name': {'key': 'displayName', 'type': 'str'},
        'category': {'key': 'category', 'type': 'str'},
        'sub_category': {'key': 'subCategory', 'type': 'str'},
        'blocked': {'key': 'blocked', 'type': 'bool'},
        'last_modified_date_time': {'key': 'lastModifiedDateTime', 'type': 'iso-8601'},
    }

    def __init__(self, *, id: str=None, number: str=None, display_name: str=None, category: str=None, sub_category: str=None, blocked: bool=None, last_modified_date_time=None, **kwargs) -> None:
        super(Account, self).__init__(**kwargs)
        self.id = id
        self.number = number
        self.display_name = display_name
        self.category = category
        self.sub_category = sub_category
        self.blocked = blocked
        self.last_modified_date_time = last_modified_date_time
