# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class BalanceSheet(Model):
    """BalanceSheet.

    :param line_number: The lineNumber property for the balanceSheet entity
    :type line_number: int
    :param display: The display property for the balanceSheet entity
    :type display: str
    :param balance: The balance property for the balanceSheet entity
    :type balance: decimal.Decimal
    :param line_type: The lineType property for the balanceSheet entity
    :type line_type: str
    :param indentation: The indentation property for the balanceSheet entity
    :type indentation: int
    :param date_filter: The dateFilter property for the balanceSheet entity
    :type date_filter: datetime
    """

    _validation = {
        'display': {'max_length': 250},
        'line_type': {'max_length': 30},
    }

    _attribute_map = {
        'line_number': {'key': 'lineNumber', 'type': 'int'},
        'display': {'key': 'display', 'type': 'str'},
        'balance': {'key': 'balance', 'type': 'decimal'},
        'line_type': {'key': 'lineType', 'type': 'str'},
        'indentation': {'key': 'indentation', 'type': 'int'},
        'date_filter': {'key': 'dateFilter', 'type': 'iso-8601'},
    }

    def __init__(self, *, line_number: int=None, display: str=None, balance=None, line_type: str=None, indentation: int=None, date_filter=None, **kwargs) -> None:
        super(BalanceSheet, self).__init__(**kwargs)
        self.line_number = line_number
        self.display = display
        self.balance = balance
        self.line_type = line_type
        self.indentation = indentation
        self.date_filter = date_filter
