# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class BodyModelModelModelModelModelModelModelModelModelModelModelModelModelModelModel(Model):
    """BodyModelModelModelModelModelModelModelModelModelModelModelModelModelModelModel.

    :param id: The id property for the timeRegistrationEntry entity
    :type id: str
    :param employee_id: The employeeId property for the timeRegistrationEntry
     entity
    :type employee_id: str
    :param employee_number: The employeeNumber property for the
     timeRegistrationEntry entity
    :type employee_number: str
    :param line_number: The lineNumber property for the timeRegistrationEntry
     entity
    :type line_number: int
    :param date_property: The date property for the timeRegistrationEntry
     entity
    :type date_property: datetime
    :param quantity: The quantity property for the timeRegistrationEntry
     entity
    :type quantity: decimal.Decimal
    :param status: The status property for the timeRegistrationEntry entity
    :type status: str
    :param unit_of_measure_id: The unitOfMeasureId property for the
     timeRegistrationEntry entity
    :type unit_of_measure_id: str
    :param unit_of_measure:
    :type unit_of_measure: ~azure.mgmt.devtestlabs.models.Unitofmeasuretype
    :param last_modfied_date_time: The lastModfiedDateTime property for the
     timeRegistrationEntry entity
    :type last_modfied_date_time: datetime
    """

    _validation = {
        'employee_number': {'max_length': 20},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'employee_id': {'key': 'employeeId', 'type': 'str'},
        'employee_number': {'key': 'employeeNumber', 'type': 'str'},
        'line_number': {'key': 'lineNumber', 'type': 'int'},
        'date_property': {'key': 'date', 'type': 'iso-8601'},
        'quantity': {'key': 'quantity', 'type': 'decimal'},
        'status': {'key': 'status', 'type': 'str'},
        'unit_of_measure_id': {'key': 'unitOfMeasureId', 'type': 'str'},
        'unit_of_measure': {'key': 'unitOfMeasure', 'type': 'Unitofmeasuretype'},
        'last_modfied_date_time': {'key': 'lastModfiedDateTime', 'type': 'iso-8601'},
    }

    def __init__(self, *, id: str=None, employee_id: str=None, employee_number: str=None, line_number: int=None, date_property=None, quantity=None, status: str=None, unit_of_measure_id: str=None, unit_of_measure=None, last_modfied_date_time=None, **kwargs) -> None:
        super(BodyModelModelModelModelModelModelModelModelModelModelModelModelModelModelModel, self).__init__(**kwargs)
        self.id = id
        self.employee_id = employee_id
        self.employee_number = employee_number
        self.line_number = line_number
        self.date_property = date_property
        self.quantity = quantity
        self.status = status
        self.unit_of_measure_id = unit_of_measure_id
        self.unit_of_measure = unit_of_measure
        self.last_modfied_date_time = last_modfied_date_time
