# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class BodyModelModelModel(Model):
    """BodyModelModelModel.

    :param id: The id property for the customer entity
    :type id: str
    :param number: The number property for the customer entity
    :type number: str
    :param display_name: The displayName property for the customer entity
    :type display_name: str
    :param type: The type property for the customer entity
    :type type: str
    :param address:
    :type address: ~azure.mgmt.devtestlabs.models.Postaladdresstype
    :param phone_number: The phoneNumber property for the customer entity
    :type phone_number: str
    :param email: The email property for the customer entity
    :type email: str
    :param website: The website property for the customer entity
    :type website: str
    :param tax_liable: The taxLiable property for the customer entity
    :type tax_liable: bool
    :param tax_area_id: The taxAreaId property for the customer entity
    :type tax_area_id: str
    :param tax_area_display_name: The taxAreaDisplayName property for the
     customer entity
    :type tax_area_display_name: str
    :param tax_registration_number: The taxRegistrationNumber property for the
     customer entity
    :type tax_registration_number: str
    :param currency_id: The currencyId property for the customer entity
    :type currency_id: str
    :param currency_code: The currencyCode property for the customer entity
    :type currency_code: str
    :param payment_terms_id: The paymentTermsId property for the customer
     entity
    :type payment_terms_id: str
    :param shipment_method_id: The shipmentMethodId property for the customer
     entity
    :type shipment_method_id: str
    :param payment_method_id: The paymentMethodId property for the customer
     entity
    :type payment_method_id: str
    :param blocked: The blocked property for the customer entity
    :type blocked: str
    :param last_modified_date_time: The lastModifiedDateTime property for the
     customer entity
    :type last_modified_date_time: datetime
    """

    _validation = {
        'number': {'max_length': 20},
        'display_name': {'max_length': 100},
        'phone_number': {'max_length': 30},
        'email': {'max_length': 80},
        'website': {'max_length': 80},
        'tax_registration_number': {'max_length': 20},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'number': {'key': 'number', 'type': 'str'},
        'display_name': {'key': 'displayName', 'type': 'str'},
        'type': {'key': 'type', 'type': 'str'},
        'address': {'key': 'address', 'type': 'Postaladdresstype'},
        'phone_number': {'key': 'phoneNumber', 'type': 'str'},
        'email': {'key': 'email', 'type': 'str'},
        'website': {'key': 'website', 'type': 'str'},
        'tax_liable': {'key': 'taxLiable', 'type': 'bool'},
        'tax_area_id': {'key': 'taxAreaId', 'type': 'str'},
        'tax_area_display_name': {'key': 'taxAreaDisplayName', 'type': 'str'},
        'tax_registration_number': {'key': 'taxRegistrationNumber', 'type': 'str'},
        'currency_id': {'key': 'currencyId', 'type': 'str'},
        'currency_code': {'key': 'currencyCode', 'type': 'str'},
        'payment_terms_id': {'key': 'paymentTermsId', 'type': 'str'},
        'shipment_method_id': {'key': 'shipmentMethodId', 'type': 'str'},
        'payment_method_id': {'key': 'paymentMethodId', 'type': 'str'},
        'blocked': {'key': 'blocked', 'type': 'str'},
        'last_modified_date_time': {'key': 'lastModifiedDateTime', 'type': 'iso-8601'},
    }

    def __init__(self, *, id: str=None, number: str=None, display_name: str=None, type: str=None, address=None, phone_number: str=None, email: str=None, website: str=None, tax_liable: bool=None, tax_area_id: str=None, tax_area_display_name: str=None, tax_registration_number: str=None, currency_id: str=None, currency_code: str=None, payment_terms_id: str=None, shipment_method_id: str=None, payment_method_id: str=None, blocked: str=None, last_modified_date_time=None, **kwargs) -> None:
        super(BodyModelModelModel, self).__init__(**kwargs)
        self.id = id
        self.number = number
        self.display_name = display_name
        self.type = type
        self.address = address
        self.phone_number = phone_number
        self.email = email
        self.website = website
        self.tax_liable = tax_liable
        self.tax_area_id = tax_area_id
        self.tax_area_display_name = tax_area_display_name
        self.tax_registration_number = tax_registration_number
        self.currency_id = currency_id
        self.currency_code = currency_code
        self.payment_terms_id = payment_terms_id
        self.shipment_method_id = shipment_method_id
        self.payment_method_id = payment_method_id
        self.blocked = blocked
        self.last_modified_date_time = last_modified_date_time
