# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class BodyModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModel(Model):
    """BodyModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModel.

    :param id: The id property for the salesQuote entity
    :type id: str
    :param number: The number property for the salesQuote entity
    :type number: str
    :param external_document_number: The externalDocumentNumber property for
     the salesQuote entity
    :type external_document_number: str
    :param document_date: The documentDate property for the salesQuote entity
    :type document_date: datetime
    :param due_date: The dueDate property for the salesQuote entity
    :type due_date: datetime
    :param customer_id: The customerId property for the salesQuote entity
    :type customer_id: str
    :param contact_id: The contactId property for the salesQuote entity
    :type contact_id: str
    :param customer_number: The customerNumber property for the salesQuote
     entity
    :type customer_number: str
    :param customer_name: The customerName property for the salesQuote entity
    :type customer_name: str
    :param bill_to_name: The billToName property for the salesQuote entity
    :type bill_to_name: str
    :param bill_to_customer_id: The billToCustomerId property for the
     salesQuote entity
    :type bill_to_customer_id: str
    :param bill_to_customer_number: The billToCustomerNumber property for the
     salesQuote entity
    :type bill_to_customer_number: str
    :param ship_to_name: The shipToName property for the salesQuote entity
    :type ship_to_name: str
    :param ship_to_contact: The shipToContact property for the salesQuote
     entity
    :type ship_to_contact: str
    :param selling_postal_address:
    :type selling_postal_address:
     ~azure.mgmt.devtestlabs.models.Postaladdresstype
    :param billing_postal_address:
    :type billing_postal_address:
     ~azure.mgmt.devtestlabs.models.Postaladdresstype
    :param shipping_postal_address:
    :type shipping_postal_address:
     ~azure.mgmt.devtestlabs.models.Postaladdresstype
    :param currency_id: The currencyId property for the salesQuote entity
    :type currency_id: str
    :param currency_code: The currencyCode property for the salesQuote entity
    :type currency_code: str
    :param payment_terms_id: The paymentTermsId property for the salesQuote
     entity
    :type payment_terms_id: str
    :param shipment_method_id: The shipmentMethodId property for the
     salesQuote entity
    :type shipment_method_id: str
    :param salesperson: The salesperson property for the salesQuote entity
    :type salesperson: str
    :param discount_amount: The discountAmount property for the salesQuote
     entity
    :type discount_amount: decimal.Decimal
    :param total_amount_excluding_tax: The totalAmountExcludingTax property
     for the salesQuote entity
    :type total_amount_excluding_tax: decimal.Decimal
    :param total_tax_amount: The totalTaxAmount property for the salesQuote
     entity
    :type total_tax_amount: decimal.Decimal
    :param total_amount_including_tax: The totalAmountIncludingTax property
     for the salesQuote entity
    :type total_amount_including_tax: decimal.Decimal
    :param status: The status property for the salesQuote entity
    :type status: str
    :param sent_date: The sentDate property for the salesQuote entity
    :type sent_date: datetime
    :param valid_until_date: The validUntilDate property for the salesQuote
     entity
    :type valid_until_date: datetime
    :param accepted_date: The acceptedDate property for the salesQuote entity
    :type accepted_date: datetime
    :param last_modified_date_time: The lastModifiedDateTime property for the
     salesQuote entity
    :type last_modified_date_time: datetime
    :param phone_number: The phoneNumber property for the salesQuote entity
    :type phone_number: str
    :param email: The email property for the salesQuote entity
    :type email: str
    """

    _validation = {
        'number': {'max_length': 20},
        'external_document_number': {'max_length': 35},
        'contact_id': {'max_length': 250},
        'customer_number': {'max_length': 20},
        'customer_name': {'max_length': 100},
        'bill_to_name': {'max_length': 100},
        'bill_to_customer_number': {'max_length': 20},
        'ship_to_name': {'max_length': 100},
        'ship_to_contact': {'max_length': 100},
        'salesperson': {'max_length': 20},
        'phone_number': {'max_length': 30},
        'email': {'max_length': 80},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'number': {'key': 'number', 'type': 'str'},
        'external_document_number': {'key': 'externalDocumentNumber', 'type': 'str'},
        'document_date': {'key': 'documentDate', 'type': 'iso-8601'},
        'due_date': {'key': 'dueDate', 'type': 'iso-8601'},
        'customer_id': {'key': 'customerId', 'type': 'str'},
        'contact_id': {'key': 'contactId', 'type': 'str'},
        'customer_number': {'key': 'customerNumber', 'type': 'str'},
        'customer_name': {'key': 'customerName', 'type': 'str'},
        'bill_to_name': {'key': 'billToName', 'type': 'str'},
        'bill_to_customer_id': {'key': 'billToCustomerId', 'type': 'str'},
        'bill_to_customer_number': {'key': 'billToCustomerNumber', 'type': 'str'},
        'ship_to_name': {'key': 'shipToName', 'type': 'str'},
        'ship_to_contact': {'key': 'shipToContact', 'type': 'str'},
        'selling_postal_address': {'key': 'sellingPostalAddress', 'type': 'Postaladdresstype'},
        'billing_postal_address': {'key': 'billingPostalAddress', 'type': 'Postaladdresstype'},
        'shipping_postal_address': {'key': 'shippingPostalAddress', 'type': 'Postaladdresstype'},
        'currency_id': {'key': 'currencyId', 'type': 'str'},
        'currency_code': {'key': 'currencyCode', 'type': 'str'},
        'payment_terms_id': {'key': 'paymentTermsId', 'type': 'str'},
        'shipment_method_id': {'key': 'shipmentMethodId', 'type': 'str'},
        'salesperson': {'key': 'salesperson', 'type': 'str'},
        'discount_amount': {'key': 'discountAmount', 'type': 'decimal'},
        'total_amount_excluding_tax': {'key': 'totalAmountExcludingTax', 'type': 'decimal'},
        'total_tax_amount': {'key': 'totalTaxAmount', 'type': 'decimal'},
        'total_amount_including_tax': {'key': 'totalAmountIncludingTax', 'type': 'decimal'},
        'status': {'key': 'status', 'type': 'str'},
        'sent_date': {'key': 'sentDate', 'type': 'iso-8601'},
        'valid_until_date': {'key': 'validUntilDate', 'type': 'iso-8601'},
        'accepted_date': {'key': 'acceptedDate', 'type': 'iso-8601'},
        'last_modified_date_time': {'key': 'lastModifiedDateTime', 'type': 'iso-8601'},
        'phone_number': {'key': 'phoneNumber', 'type': 'str'},
        'email': {'key': 'email', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(BodyModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModel, self).__init__(**kwargs)
        self.id = kwargs.get('id', None)
        self.number = kwargs.get('number', None)
        self.external_document_number = kwargs.get('external_document_number', None)
        self.document_date = kwargs.get('document_date', None)
        self.due_date = kwargs.get('due_date', None)
        self.customer_id = kwargs.get('customer_id', None)
        self.contact_id = kwargs.get('contact_id', None)
        self.customer_number = kwargs.get('customer_number', None)
        self.customer_name = kwargs.get('customer_name', None)
        self.bill_to_name = kwargs.get('bill_to_name', None)
        self.bill_to_customer_id = kwargs.get('bill_to_customer_id', None)
        self.bill_to_customer_number = kwargs.get('bill_to_customer_number', None)
        self.ship_to_name = kwargs.get('ship_to_name', None)
        self.ship_to_contact = kwargs.get('ship_to_contact', None)
        self.selling_postal_address = kwargs.get('selling_postal_address', None)
        self.billing_postal_address = kwargs.get('billing_postal_address', None)
        self.shipping_postal_address = kwargs.get('shipping_postal_address', None)
        self.currency_id = kwargs.get('currency_id', None)
        self.currency_code = kwargs.get('currency_code', None)
        self.payment_terms_id = kwargs.get('payment_terms_id', None)
        self.shipment_method_id = kwargs.get('shipment_method_id', None)
        self.salesperson = kwargs.get('salesperson', None)
        self.discount_amount = kwargs.get('discount_amount', None)
        self.total_amount_excluding_tax = kwargs.get('total_amount_excluding_tax', None)
        self.total_tax_amount = kwargs.get('total_tax_amount', None)
        self.total_amount_including_tax = kwargs.get('total_amount_including_tax', None)
        self.status = kwargs.get('status', None)
        self.sent_date = kwargs.get('sent_date', None)
        self.valid_until_date = kwargs.get('valid_until_date', None)
        self.accepted_date = kwargs.get('accepted_date', None)
        self.last_modified_date_time = kwargs.get('last_modified_date_time', None)
        self.phone_number = kwargs.get('phone_number', None)
        self.email = kwargs.get('email', None)
