# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class BodyModelModelModelModelModelModel(Model):
    """BodyModelModelModelModelModelModel.

    :param id: The id property for the salesInvoice entity
    :type id: str
    :param number: The number property for the salesInvoice entity
    :type number: str
    :param external_document_number: The externalDocumentNumber property for
     the salesInvoice entity
    :type external_document_number: str
    :param invoice_date: The invoiceDate property for the salesInvoice entity
    :type invoice_date: datetime
    :param due_date: The dueDate property for the salesInvoice entity
    :type due_date: datetime
    :param customer_purchase_order_reference: The
     customerPurchaseOrderReference property for the salesInvoice entity
    :type customer_purchase_order_reference: str
    :param customer_id: The customerId property for the salesInvoice entity
    :type customer_id: str
    :param contact_id: The contactId property for the salesInvoice entity
    :type contact_id: str
    :param customer_number: The customerNumber property for the salesInvoice
     entity
    :type customer_number: str
    :param customer_name: The customerName property for the salesInvoice
     entity
    :type customer_name: str
    :param bill_to_name: The billToName property for the salesInvoice entity
    :type bill_to_name: str
    :param bill_to_customer_id: The billToCustomerId property for the
     salesInvoice entity
    :type bill_to_customer_id: str
    :param bill_to_customer_number: The billToCustomerNumber property for the
     salesInvoice entity
    :type bill_to_customer_number: str
    :param ship_to_name: The shipToName property for the salesInvoice entity
    :type ship_to_name: str
    :param ship_to_contact: The shipToContact property for the salesInvoice
     entity
    :type ship_to_contact: str
    :param selling_postal_address:
    :type selling_postal_address:
     ~azure.mgmt.devtestlabs.models.Postaladdresstype
    :param billing_postal_address:
    :type billing_postal_address:
     ~azure.mgmt.devtestlabs.models.Postaladdresstype
    :param shipping_postal_address:
    :type shipping_postal_address:
     ~azure.mgmt.devtestlabs.models.Postaladdresstype
    :param currency_id: The currencyId property for the salesInvoice entity
    :type currency_id: str
    :param currency_code: The currencyCode property for the salesInvoice
     entity
    :type currency_code: str
    :param order_id: The orderId property for the salesInvoice entity
    :type order_id: str
    :param order_number: The orderNumber property for the salesInvoice entity
    :type order_number: str
    :param payment_terms_id: The paymentTermsId property for the salesInvoice
     entity
    :type payment_terms_id: str
    :param shipment_method_id: The shipmentMethodId property for the
     salesInvoice entity
    :type shipment_method_id: str
    :param salesperson: The salesperson property for the salesInvoice entity
    :type salesperson: str
    :param prices_include_tax: The pricesIncludeTax property for the
     salesInvoice entity
    :type prices_include_tax: bool
    :param discount_amount: The discountAmount property for the salesInvoice
     entity
    :type discount_amount: decimal.Decimal
    :param discount_applied_before_tax: The discountAppliedBeforeTax property
     for the salesInvoice entity
    :type discount_applied_before_tax: bool
    :param total_amount_excluding_tax: The totalAmountExcludingTax property
     for the salesInvoice entity
    :type total_amount_excluding_tax: decimal.Decimal
    :param total_tax_amount: The totalTaxAmount property for the salesInvoice
     entity
    :type total_tax_amount: decimal.Decimal
    :param total_amount_including_tax: The totalAmountIncludingTax property
     for the salesInvoice entity
    :type total_amount_including_tax: decimal.Decimal
    :param status: The status property for the salesInvoice entity
    :type status: str
    :param last_modified_date_time: The lastModifiedDateTime property for the
     salesInvoice entity
    :type last_modified_date_time: datetime
    :param phone_number: The phoneNumber property for the salesInvoice entity
    :type phone_number: str
    :param email: The email property for the salesInvoice entity
    :type email: str
    """

    _validation = {
        'number': {'max_length': 20},
        'external_document_number': {'max_length': 35},
        'customer_purchase_order_reference': {'max_length': 35},
        'contact_id': {'max_length': 250},
        'customer_number': {'max_length': 20},
        'customer_name': {'max_length': 100},
        'bill_to_name': {'max_length': 100},
        'bill_to_customer_number': {'max_length': 20},
        'ship_to_name': {'max_length': 100},
        'ship_to_contact': {'max_length': 100},
        'order_number': {'max_length': 20},
        'salesperson': {'max_length': 20},
        'phone_number': {'max_length': 30},
        'email': {'max_length': 80},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'number': {'key': 'number', 'type': 'str'},
        'external_document_number': {'key': 'externalDocumentNumber', 'type': 'str'},
        'invoice_date': {'key': 'invoiceDate', 'type': 'iso-8601'},
        'due_date': {'key': 'dueDate', 'type': 'iso-8601'},
        'customer_purchase_order_reference': {'key': 'customerPurchaseOrderReference', 'type': 'str'},
        'customer_id': {'key': 'customerId', 'type': 'str'},
        'contact_id': {'key': 'contactId', 'type': 'str'},
        'customer_number': {'key': 'customerNumber', 'type': 'str'},
        'customer_name': {'key': 'customerName', 'type': 'str'},
        'bill_to_name': {'key': 'billToName', 'type': 'str'},
        'bill_to_customer_id': {'key': 'billToCustomerId', 'type': 'str'},
        'bill_to_customer_number': {'key': 'billToCustomerNumber', 'type': 'str'},
        'ship_to_name': {'key': 'shipToName', 'type': 'str'},
        'ship_to_contact': {'key': 'shipToContact', 'type': 'str'},
        'selling_postal_address': {'key': 'sellingPostalAddress', 'type': 'Postaladdresstype'},
        'billing_postal_address': {'key': 'billingPostalAddress', 'type': 'Postaladdresstype'},
        'shipping_postal_address': {'key': 'shippingPostalAddress', 'type': 'Postaladdresstype'},
        'currency_id': {'key': 'currencyId', 'type': 'str'},
        'currency_code': {'key': 'currencyCode', 'type': 'str'},
        'order_id': {'key': 'orderId', 'type': 'str'},
        'order_number': {'key': 'orderNumber', 'type': 'str'},
        'payment_terms_id': {'key': 'paymentTermsId', 'type': 'str'},
        'shipment_method_id': {'key': 'shipmentMethodId', 'type': 'str'},
        'salesperson': {'key': 'salesperson', 'type': 'str'},
        'prices_include_tax': {'key': 'pricesIncludeTax', 'type': 'bool'},
        'discount_amount': {'key': 'discountAmount', 'type': 'decimal'},
        'discount_applied_before_tax': {'key': 'discountAppliedBeforeTax', 'type': 'bool'},
        'total_amount_excluding_tax': {'key': 'totalAmountExcludingTax', 'type': 'decimal'},
        'total_tax_amount': {'key': 'totalTaxAmount', 'type': 'decimal'},
        'total_amount_including_tax': {'key': 'totalAmountIncludingTax', 'type': 'decimal'},
        'status': {'key': 'status', 'type': 'str'},
        'last_modified_date_time': {'key': 'lastModifiedDateTime', 'type': 'iso-8601'},
        'phone_number': {'key': 'phoneNumber', 'type': 'str'},
        'email': {'key': 'email', 'type': 'str'},
    }

    def __init__(self, *, id: str=None, number: str=None, external_document_number: str=None, invoice_date=None, due_date=None, customer_purchase_order_reference: str=None, customer_id: str=None, contact_id: str=None, customer_number: str=None, customer_name: str=None, bill_to_name: str=None, bill_to_customer_id: str=None, bill_to_customer_number: str=None, ship_to_name: str=None, ship_to_contact: str=None, selling_postal_address=None, billing_postal_address=None, shipping_postal_address=None, currency_id: str=None, currency_code: str=None, order_id: str=None, order_number: str=None, payment_terms_id: str=None, shipment_method_id: str=None, salesperson: str=None, prices_include_tax: bool=None, discount_amount=None, discount_applied_before_tax: bool=None, total_amount_excluding_tax=None, total_tax_amount=None, total_amount_including_tax=None, status: str=None, last_modified_date_time=None, phone_number: str=None, email: str=None, **kwargs) -> None:
        super(BodyModelModelModelModelModelModel, self).__init__(**kwargs)
        self.id = id
        self.number = number
        self.external_document_number = external_document_number
        self.invoice_date = invoice_date
        self.due_date = due_date
        self.customer_purchase_order_reference = customer_purchase_order_reference
        self.customer_id = customer_id
        self.contact_id = contact_id
        self.customer_number = customer_number
        self.customer_name = customer_name
        self.bill_to_name = bill_to_name
        self.bill_to_customer_id = bill_to_customer_id
        self.bill_to_customer_number = bill_to_customer_number
        self.ship_to_name = ship_to_name
        self.ship_to_contact = ship_to_contact
        self.selling_postal_address = selling_postal_address
        self.billing_postal_address = billing_postal_address
        self.shipping_postal_address = shipping_postal_address
        self.currency_id = currency_id
        self.currency_code = currency_code
        self.order_id = order_id
        self.order_number = order_number
        self.payment_terms_id = payment_terms_id
        self.shipment_method_id = shipment_method_id
        self.salesperson = salesperson
        self.prices_include_tax = prices_include_tax
        self.discount_amount = discount_amount
        self.discount_applied_before_tax = discount_applied_before_tax
        self.total_amount_excluding_tax = total_amount_excluding_tax
        self.total_tax_amount = total_tax_amount
        self.total_amount_including_tax = total_amount_including_tax
        self.status = status
        self.last_modified_date_time = last_modified_date_time
        self.phone_number = phone_number
        self.email = email
