# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class BodyModelModel(Model):
    """BodyModelModel.

    :param parent_id: The parentId property for the defaultDimensions entity
    :type parent_id: str
    :param dimension_id: The dimensionId property for the defaultDimensions
     entity
    :type dimension_id: str
    :param dimension_code: The dimensionCode property for the
     defaultDimensions entity
    :type dimension_code: str
    :param dimension_value_id: The dimensionValueId property for the
     defaultDimensions entity
    :type dimension_value_id: str
    :param dimension_value_code: The dimensionValueCode property for the
     defaultDimensions entity
    :type dimension_value_code: str
    :param posting_validation: The postingValidation property for the
     defaultDimensions entity
    :type posting_validation: str
    """

    _validation = {
        'dimension_code': {'max_length': 20},
        'dimension_value_code': {'max_length': 20},
    }

    _attribute_map = {
        'parent_id': {'key': 'parentId', 'type': 'str'},
        'dimension_id': {'key': 'dimensionId', 'type': 'str'},
        'dimension_code': {'key': 'dimensionCode', 'type': 'str'},
        'dimension_value_id': {'key': 'dimensionValueId', 'type': 'str'},
        'dimension_value_code': {'key': 'dimensionValueCode', 'type': 'str'},
        'posting_validation': {'key': 'postingValidation', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(BodyModelModel, self).__init__(**kwargs)
        self.parent_id = kwargs.get('parent_id', None)
        self.dimension_id = kwargs.get('dimension_id', None)
        self.dimension_code = kwargs.get('dimension_code', None)
        self.dimension_value_id = kwargs.get('dimension_value_id', None)
        self.dimension_value_code = kwargs.get('dimension_value_code', None)
        self.posting_validation = kwargs.get('posting_validation', None)
