# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class BodyModelModelModelModelModel(Model):
    """BodyModelModelModelModelModel.

    :param id: The id property for the companyInformation entity
    :type id: str
    :param display_name: The displayName property for the companyInformation
     entity
    :type display_name: str
    :param address:
    :type address: ~azure.mgmt.devtestlabs.models.Postaladdresstype
    :param phone_number: The phoneNumber property for the companyInformation
     entity
    :type phone_number: str
    :param fax_number: The faxNumber property for the companyInformation
     entity
    :type fax_number: str
    :param email: The email property for the companyInformation entity
    :type email: str
    :param website: The website property for the companyInformation entity
    :type website: str
    :param tax_registration_number: The taxRegistrationNumber property for the
     companyInformation entity
    :type tax_registration_number: str
    :param currency_code: The currencyCode property for the companyInformation
     entity
    :type currency_code: str
    :param current_fiscal_year_start_date: The currentFiscalYearStartDate
     property for the companyInformation entity
    :type current_fiscal_year_start_date: datetime
    :param industry: The industry property for the companyInformation entity
    :type industry: str
    :param picture: The picture property for the companyInformation entity
    :type picture: str
    :param last_modified_date_time: The lastModifiedDateTime property for the
     companyInformation entity
    :type last_modified_date_time: datetime
    """

    _validation = {
        'display_name': {'max_length': 100},
        'phone_number': {'max_length': 30},
        'fax_number': {'max_length': 30},
        'email': {'max_length': 80},
        'website': {'max_length': 80},
        'tax_registration_number': {'max_length': 20},
        'industry': {'max_length': 30},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'display_name': {'key': 'displayName', 'type': 'str'},
        'address': {'key': 'address', 'type': 'Postaladdresstype'},
        'phone_number': {'key': 'phoneNumber', 'type': 'str'},
        'fax_number': {'key': 'faxNumber', 'type': 'str'},
        'email': {'key': 'email', 'type': 'str'},
        'website': {'key': 'website', 'type': 'str'},
        'tax_registration_number': {'key': 'taxRegistrationNumber', 'type': 'str'},
        'currency_code': {'key': 'currencyCode', 'type': 'str'},
        'current_fiscal_year_start_date': {'key': 'currentFiscalYearStartDate', 'type': 'iso-8601'},
        'industry': {'key': 'industry', 'type': 'str'},
        'picture': {'key': 'picture', 'type': 'str'},
        'last_modified_date_time': {'key': 'lastModifiedDateTime', 'type': 'iso-8601'},
    }

    def __init__(self, *, id: str=None, display_name: str=None, address=None, phone_number: str=None, fax_number: str=None, email: str=None, website: str=None, tax_registration_number: str=None, currency_code: str=None, current_fiscal_year_start_date=None, industry: str=None, picture: str=None, last_modified_date_time=None, **kwargs) -> None:
        super(BodyModelModelModelModelModel, self).__init__(**kwargs)
        self.id = id
        self.display_name = display_name
        self.address = address
        self.phone_number = phone_number
        self.fax_number = fax_number
        self.email = email
        self.website = website
        self.tax_registration_number = tax_registration_number
        self.currency_code = currency_code
        self.current_fiscal_year_start_date = current_fiscal_year_start_date
        self.industry = industry
        self.picture = picture
        self.last_modified_date_time = last_modified_date_time
