# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class BodyModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModel(Model):
    """BodyModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModel.

    :param general_ledger_entry_number: The generalLedgerEntryNumber property
     for the generalLedgerEntryAttachments entity
    :type general_ledger_entry_number: int
    :param id: The id property for the generalLedgerEntryAttachments entity
    :type id: str
    :param file_name: The fileName property for the
     generalLedgerEntryAttachments entity
    :type file_name: str
    :param byte_size: The byteSize property for the
     generalLedgerEntryAttachments entity
    :type byte_size: int
    :param content: The content property for the generalLedgerEntryAttachments
     entity
    :type content: str
    :param created_date_time: The createdDateTime property for the
     generalLedgerEntryAttachments entity
    :type created_date_time: datetime
    """

    _validation = {
        'file_name': {'max_length': 250},
    }

    _attribute_map = {
        'general_ledger_entry_number': {'key': 'generalLedgerEntryNumber', 'type': 'int'},
        'id': {'key': 'id', 'type': 'str'},
        'file_name': {'key': 'fileName', 'type': 'str'},
        'byte_size': {'key': 'byteSize', 'type': 'int'},
        'content': {'key': 'content', 'type': 'str'},
        'created_date_time': {'key': 'createdDateTime', 'type': 'iso-8601'},
    }

    def __init__(self, **kwargs):
        super(BodyModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModel, self).__init__(**kwargs)
        self.general_ledger_entry_number = kwargs.get('general_ledger_entry_number', None)
        self.id = kwargs.get('id', None)
        self.file_name = kwargs.get('file_name', None)
        self.byte_size = kwargs.get('byte_size', None)
        self.content = kwargs.get('content', None)
        self.created_date_time = kwargs.get('created_date_time', None)
