# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class BodyModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModel(Model):
    """BodyModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModel.

    :param id: The id property for the paymentTerm entity
    :type id: str
    :param code: The code property for the paymentTerm entity
    :type code: str
    :param display_name: The displayName property for the paymentTerm entity
    :type display_name: str
    :param due_date_calculation: The dueDateCalculation property for the
     paymentTerm entity
    :type due_date_calculation: str
    :param discount_date_calculation: The discountDateCalculation property for
     the paymentTerm entity
    :type discount_date_calculation: str
    :param discount_percent: The discountPercent property for the paymentTerm
     entity
    :type discount_percent: decimal.Decimal
    :param calculate_discount_on_credit_memos: The
     calculateDiscountOnCreditMemos property for the paymentTerm entity
    :type calculate_discount_on_credit_memos: bool
    :param last_modified_date_time: The lastModifiedDateTime property for the
     paymentTerm entity
    :type last_modified_date_time: datetime
    """

    _validation = {
        'code': {'max_length': 10},
        'display_name': {'max_length': 100},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'code': {'key': 'code', 'type': 'str'},
        'display_name': {'key': 'displayName', 'type': 'str'},
        'due_date_calculation': {'key': 'dueDateCalculation', 'type': 'str'},
        'discount_date_calculation': {'key': 'discountDateCalculation', 'type': 'str'},
        'discount_percent': {'key': 'discountPercent', 'type': 'decimal'},
        'calculate_discount_on_credit_memos': {'key': 'calculateDiscountOnCreditMemos', 'type': 'bool'},
        'last_modified_date_time': {'key': 'lastModifiedDateTime', 'type': 'iso-8601'},
    }

    def __init__(self, **kwargs):
        super(BodyModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModel, self).__init__(**kwargs)
        self.id = kwargs.get('id', None)
        self.code = kwargs.get('code', None)
        self.display_name = kwargs.get('display_name', None)
        self.due_date_calculation = kwargs.get('due_date_calculation', None)
        self.discount_date_calculation = kwargs.get('discount_date_calculation', None)
        self.discount_percent = kwargs.get('discount_percent', None)
        self.calculate_discount_on_credit_memos = kwargs.get('calculate_discount_on_credit_memos', None)
        self.last_modified_date_time = kwargs.get('last_modified_date_time', None)
