# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class Company(Model):
    """Company.

    :param id: The id property for the company entity
    :type id: str
    :param system_version: The systemVersion property for the company entity
    :type system_version: str
    :param name: The name property for the company entity
    :type name: str
    :param display_name: The displayName property for the company entity
    :type display_name: str
    :param business_profile_id: The businessProfileId property for the company
     entity
    :type business_profile_id: str
    :param items:
    :type items: list[~azure.mgmt.devtestlabs.models.Item]
    :param picture:
    :type picture: list[~azure.mgmt.devtestlabs.models.Picture]
    :param default_dimensions:
    :type default_dimensions:
     list[~azure.mgmt.devtestlabs.models.DefaultDimensions]
    :param customers:
    :type customers: list[~azure.mgmt.devtestlabs.models.Customer]
    :param customer_financial_details:
    :type customer_financial_details:
     list[~azure.mgmt.devtestlabs.models.CustomerFinancialDetail]
    :param vendors:
    :type vendors: list[~azure.mgmt.devtestlabs.models.Vendor]
    :param company_information:
    :type company_information:
     list[~azure.mgmt.devtestlabs.models.CompanyInformation]
    :param sales_invoices:
    :type sales_invoices: list[~azure.mgmt.devtestlabs.models.SalesInvoice]
    :param sales_invoice_lines:
    :type sales_invoice_lines:
     list[~azure.mgmt.devtestlabs.models.SalesInvoiceLine]
    :param pdf_document:
    :type pdf_document: list[~azure.mgmt.devtestlabs.models.PdfDocument]
    :param customer_payment_journals:
    :type customer_payment_journals:
     list[~azure.mgmt.devtestlabs.models.CustomerPaymentJournal]
    :param customer_payments:
    :type customer_payments:
     list[~azure.mgmt.devtestlabs.models.CustomerPayment]
    :param accounts:
    :type accounts: list[~azure.mgmt.devtestlabs.models.Account]
    :param tax_groups:
    :type tax_groups: list[~azure.mgmt.devtestlabs.models.TaxGroup]
    :param journals:
    :type journals: list[~azure.mgmt.devtestlabs.models.Journal]
    :param journal_lines:
    :type journal_lines: list[~azure.mgmt.devtestlabs.models.JournalLine]
    :param attachments:
    :type attachments: list[~azure.mgmt.devtestlabs.models.Attachments]
    :param employees:
    :type employees: list[~azure.mgmt.devtestlabs.models.Employee]
    :param time_registration_entries:
    :type time_registration_entries:
     list[~azure.mgmt.devtestlabs.models.TimeRegistrationEntry]
    :param general_ledger_entries:
    :type general_ledger_entries:
     list[~azure.mgmt.devtestlabs.models.GeneralLedgerEntry]
    :param currencies:
    :type currencies: list[~azure.mgmt.devtestlabs.models.Currency]
    :param payment_methods:
    :type payment_methods: list[~azure.mgmt.devtestlabs.models.PaymentMethod]
    :param dimensions:
    :type dimensions: list[~azure.mgmt.devtestlabs.models.Dimension]
    :param dimension_values:
    :type dimension_values:
     list[~azure.mgmt.devtestlabs.models.DimensionValue]
    :param dimension_lines:
    :type dimension_lines: list[~azure.mgmt.devtestlabs.models.DimensionLine]
    :param payment_terms:
    :type payment_terms: list[~azure.mgmt.devtestlabs.models.PaymentTerm]
    :param shipment_methods:
    :type shipment_methods:
     list[~azure.mgmt.devtestlabs.models.ShipmentMethod]
    :param item_categories:
    :type item_categories: list[~azure.mgmt.devtestlabs.models.ItemCategory]
    :param cash_flow_statement:
    :type cash_flow_statement:
     list[~azure.mgmt.devtestlabs.models.CashFlowStatement]
    :param countries_regions:
    :type countries_regions:
     list[~azure.mgmt.devtestlabs.models.CountryRegion]
    :param sales_orders:
    :type sales_orders: list[~azure.mgmt.devtestlabs.models.SalesOrder]
    :param sales_order_lines:
    :type sales_order_lines:
     list[~azure.mgmt.devtestlabs.models.SalesOrderLine]
    :param retained_earnings_statement:
    :type retained_earnings_statement:
     list[~azure.mgmt.devtestlabs.models.RetainedEarningsStatement]
    :param units_of_measure:
    :type units_of_measure: list[~azure.mgmt.devtestlabs.models.UnitOfMeasure]
    :param aged_accounts_receivable:
    :type aged_accounts_receivable:
     list[~azure.mgmt.devtestlabs.models.AgedAccountsReceivable]
    :param aged_accounts_payable:
    :type aged_accounts_payable:
     list[~azure.mgmt.devtestlabs.models.AgedAccountsPayable]
    :param balance_sheet:
    :type balance_sheet: list[~azure.mgmt.devtestlabs.models.BalanceSheet]
    :param trial_balance:
    :type trial_balance: list[~azure.mgmt.devtestlabs.models.TrialBalance]
    :param income_statement:
    :type income_statement:
     list[~azure.mgmt.devtestlabs.models.IncomeStatement]
    :param tax_areas:
    :type tax_areas: list[~azure.mgmt.devtestlabs.models.TaxArea]
    :param sales_quotes:
    :type sales_quotes: list[~azure.mgmt.devtestlabs.models.SalesQuote]
    :param sales_quote_lines:
    :type sales_quote_lines:
     list[~azure.mgmt.devtestlabs.models.SalesQuoteLine]
    :param sales_credit_memos:
    :type sales_credit_memos:
     list[~azure.mgmt.devtestlabs.models.SalesCreditMemo]
    :param sales_credit_memo_lines:
    :type sales_credit_memo_lines:
     list[~azure.mgmt.devtestlabs.models.SalesCreditMemoLine]
    :param general_ledger_entry_attachments:
    :type general_ledger_entry_attachments:
     list[~azure.mgmt.devtestlabs.models.GeneralLedgerEntryAttachments]
    :param purchase_invoices:
    :type purchase_invoices:
     list[~azure.mgmt.devtestlabs.models.PurchaseInvoice]
    :param purchase_invoice_lines:
    :type purchase_invoice_lines:
     list[~azure.mgmt.devtestlabs.models.PurchaseInvoiceLine]
    :param customer_sales:
    :type customer_sales: list[~azure.mgmt.devtestlabs.models.CustomerSale]
    :param vendor_purchases:
    :type vendor_purchases:
     list[~azure.mgmt.devtestlabs.models.VendorPurchase]
    """

    _validation = {
        'name': {'max_length': 30},
        'display_name': {'max_length': 250},
        'business_profile_id': {'max_length': 250},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'system_version': {'key': 'systemVersion', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'display_name': {'key': 'displayName', 'type': 'str'},
        'business_profile_id': {'key': 'businessProfileId', 'type': 'str'},
        'items': {'key': 'items', 'type': '[Item]'},
        'picture': {'key': 'picture', 'type': '[Picture]'},
        'default_dimensions': {'key': 'defaultDimensions', 'type': '[DefaultDimensions]'},
        'customers': {'key': 'customers', 'type': '[Customer]'},
        'customer_financial_details': {'key': 'customerFinancialDetails', 'type': '[CustomerFinancialDetail]'},
        'vendors': {'key': 'vendors', 'type': '[Vendor]'},
        'company_information': {'key': 'companyInformation', 'type': '[CompanyInformation]'},
        'sales_invoices': {'key': 'salesInvoices', 'type': '[SalesInvoice]'},
        'sales_invoice_lines': {'key': 'salesInvoiceLines', 'type': '[SalesInvoiceLine]'},
        'pdf_document': {'key': 'pdfDocument', 'type': '[PdfDocument]'},
        'customer_payment_journals': {'key': 'customerPaymentJournals', 'type': '[CustomerPaymentJournal]'},
        'customer_payments': {'key': 'customerPayments', 'type': '[CustomerPayment]'},
        'accounts': {'key': 'accounts', 'type': '[Account]'},
        'tax_groups': {'key': 'taxGroups', 'type': '[TaxGroup]'},
        'journals': {'key': 'journals', 'type': '[Journal]'},
        'journal_lines': {'key': 'journalLines', 'type': '[JournalLine]'},
        'attachments': {'key': 'attachments', 'type': '[Attachments]'},
        'employees': {'key': 'employees', 'type': '[Employee]'},
        'time_registration_entries': {'key': 'timeRegistrationEntries', 'type': '[TimeRegistrationEntry]'},
        'general_ledger_entries': {'key': 'generalLedgerEntries', 'type': '[GeneralLedgerEntry]'},
        'currencies': {'key': 'currencies', 'type': '[Currency]'},
        'payment_methods': {'key': 'paymentMethods', 'type': '[PaymentMethod]'},
        'dimensions': {'key': 'dimensions', 'type': '[Dimension]'},
        'dimension_values': {'key': 'dimensionValues', 'type': '[DimensionValue]'},
        'dimension_lines': {'key': 'dimensionLines', 'type': '[DimensionLine]'},
        'payment_terms': {'key': 'paymentTerms', 'type': '[PaymentTerm]'},
        'shipment_methods': {'key': 'shipmentMethods', 'type': '[ShipmentMethod]'},
        'item_categories': {'key': 'itemCategories', 'type': '[ItemCategory]'},
        'cash_flow_statement': {'key': 'cashFlowStatement', 'type': '[CashFlowStatement]'},
        'countries_regions': {'key': 'countriesRegions', 'type': '[CountryRegion]'},
        'sales_orders': {'key': 'salesOrders', 'type': '[SalesOrder]'},
        'sales_order_lines': {'key': 'salesOrderLines', 'type': '[SalesOrderLine]'},
        'retained_earnings_statement': {'key': 'retainedEarningsStatement', 'type': '[RetainedEarningsStatement]'},
        'units_of_measure': {'key': 'unitsOfMeasure', 'type': '[UnitOfMeasure]'},
        'aged_accounts_receivable': {'key': 'agedAccountsReceivable', 'type': '[AgedAccountsReceivable]'},
        'aged_accounts_payable': {'key': 'agedAccountsPayable', 'type': '[AgedAccountsPayable]'},
        'balance_sheet': {'key': 'balanceSheet', 'type': '[BalanceSheet]'},
        'trial_balance': {'key': 'trialBalance', 'type': '[TrialBalance]'},
        'income_statement': {'key': 'incomeStatement', 'type': '[IncomeStatement]'},
        'tax_areas': {'key': 'taxAreas', 'type': '[TaxArea]'},
        'sales_quotes': {'key': 'salesQuotes', 'type': '[SalesQuote]'},
        'sales_quote_lines': {'key': 'salesQuoteLines', 'type': '[SalesQuoteLine]'},
        'sales_credit_memos': {'key': 'salesCreditMemos', 'type': '[SalesCreditMemo]'},
        'sales_credit_memo_lines': {'key': 'salesCreditMemoLines', 'type': '[SalesCreditMemoLine]'},
        'general_ledger_entry_attachments': {'key': 'generalLedgerEntryAttachments', 'type': '[GeneralLedgerEntryAttachments]'},
        'purchase_invoices': {'key': 'purchaseInvoices', 'type': '[PurchaseInvoice]'},
        'purchase_invoice_lines': {'key': 'purchaseInvoiceLines', 'type': '[PurchaseInvoiceLine]'},
        'customer_sales': {'key': 'customerSales', 'type': '[CustomerSale]'},
        'vendor_purchases': {'key': 'vendorPurchases', 'type': '[VendorPurchase]'},
    }

    def __init__(self, **kwargs):
        super(Company, self).__init__(**kwargs)
        self.id = kwargs.get('id', None)
        self.system_version = kwargs.get('system_version', None)
        self.name = kwargs.get('name', None)
        self.display_name = kwargs.get('display_name', None)
        self.business_profile_id = kwargs.get('business_profile_id', None)
        self.items = kwargs.get('items', None)
        self.picture = kwargs.get('picture', None)
        self.default_dimensions = kwargs.get('default_dimensions', None)
        self.customers = kwargs.get('customers', None)
        self.customer_financial_details = kwargs.get('customer_financial_details', None)
        self.vendors = kwargs.get('vendors', None)
        self.company_information = kwargs.get('company_information', None)
        self.sales_invoices = kwargs.get('sales_invoices', None)
        self.sales_invoice_lines = kwargs.get('sales_invoice_lines', None)
        self.pdf_document = kwargs.get('pdf_document', None)
        self.customer_payment_journals = kwargs.get('customer_payment_journals', None)
        self.customer_payments = kwargs.get('customer_payments', None)
        self.accounts = kwargs.get('accounts', None)
        self.tax_groups = kwargs.get('tax_groups', None)
        self.journals = kwargs.get('journals', None)
        self.journal_lines = kwargs.get('journal_lines', None)
        self.attachments = kwargs.get('attachments', None)
        self.employees = kwargs.get('employees', None)
        self.time_registration_entries = kwargs.get('time_registration_entries', None)
        self.general_ledger_entries = kwargs.get('general_ledger_entries', None)
        self.currencies = kwargs.get('currencies', None)
        self.payment_methods = kwargs.get('payment_methods', None)
        self.dimensions = kwargs.get('dimensions', None)
        self.dimension_values = kwargs.get('dimension_values', None)
        self.dimension_lines = kwargs.get('dimension_lines', None)
        self.payment_terms = kwargs.get('payment_terms', None)
        self.shipment_methods = kwargs.get('shipment_methods', None)
        self.item_categories = kwargs.get('item_categories', None)
        self.cash_flow_statement = kwargs.get('cash_flow_statement', None)
        self.countries_regions = kwargs.get('countries_regions', None)
        self.sales_orders = kwargs.get('sales_orders', None)
        self.sales_order_lines = kwargs.get('sales_order_lines', None)
        self.retained_earnings_statement = kwargs.get('retained_earnings_statement', None)
        self.units_of_measure = kwargs.get('units_of_measure', None)
        self.aged_accounts_receivable = kwargs.get('aged_accounts_receivable', None)
        self.aged_accounts_payable = kwargs.get('aged_accounts_payable', None)
        self.balance_sheet = kwargs.get('balance_sheet', None)
        self.trial_balance = kwargs.get('trial_balance', None)
        self.income_statement = kwargs.get('income_statement', None)
        self.tax_areas = kwargs.get('tax_areas', None)
        self.sales_quotes = kwargs.get('sales_quotes', None)
        self.sales_quote_lines = kwargs.get('sales_quote_lines', None)
        self.sales_credit_memos = kwargs.get('sales_credit_memos', None)
        self.sales_credit_memo_lines = kwargs.get('sales_credit_memo_lines', None)
        self.general_ledger_entry_attachments = kwargs.get('general_ledger_entry_attachments', None)
        self.purchase_invoices = kwargs.get('purchase_invoices', None)
        self.purchase_invoice_lines = kwargs.get('purchase_invoice_lines', None)
        self.customer_sales = kwargs.get('customer_sales', None)
        self.vendor_purchases = kwargs.get('vendor_purchases', None)
