# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class Company(Model):
    """Company.

    :param id: The id property for the company entity
    :type id: str
    :param system_version: The systemVersion property for the company entity
    :type system_version: str
    :param name: The name property for the company entity
    :type name: str
    :param display_name: The displayName property for the company entity
    :type display_name: str
    :param business_profile_id: The businessProfileId property for the company
     entity
    :type business_profile_id: str
    :param items:
    :type items: list[~azure.mgmt.devtestlabs.models.Item]
    :param picture:
    :type picture: list[~azure.mgmt.devtestlabs.models.Picture]
    :param default_dimensions:
    :type default_dimensions:
     list[~azure.mgmt.devtestlabs.models.DefaultDimensions]
    :param customers:
    :type customers: list[~azure.mgmt.devtestlabs.models.Customer]
    :param customer_financial_details:
    :type customer_financial_details:
     list[~azure.mgmt.devtestlabs.models.CustomerFinancialDetail]
    :param vendors:
    :type vendors: list[~azure.mgmt.devtestlabs.models.Vendor]
    :param company_information:
    :type company_information:
     list[~azure.mgmt.devtestlabs.models.CompanyInformation]
    :param sales_invoices:
    :type sales_invoices: list[~azure.mgmt.devtestlabs.models.SalesInvoice]
    :param sales_invoice_lines:
    :type sales_invoice_lines:
     list[~azure.mgmt.devtestlabs.models.SalesInvoiceLine]
    :param pdf_document:
    :type pdf_document: list[~azure.mgmt.devtestlabs.models.PdfDocument]
    :param customer_payment_journals:
    :type customer_payment_journals:
     list[~azure.mgmt.devtestlabs.models.CustomerPaymentJournal]
    :param customer_payments:
    :type customer_payments:
     list[~azure.mgmt.devtestlabs.models.CustomerPayment]
    :param accounts:
    :type accounts: list[~azure.mgmt.devtestlabs.models.Account]
    :param tax_groups:
    :type tax_groups: list[~azure.mgmt.devtestlabs.models.TaxGroup]
    :param journals:
    :type journals: list[~azure.mgmt.devtestlabs.models.Journal]
    :param journal_lines:
    :type journal_lines: list[~azure.mgmt.devtestlabs.models.JournalLine]
    :param attachments:
    :type attachments: list[~azure.mgmt.devtestlabs.models.Attachments]
    :param employees:
    :type employees: list[~azure.mgmt.devtestlabs.models.Employee]
    :param time_registration_entries:
    :type time_registration_entries:
     list[~azure.mgmt.devtestlabs.models.TimeRegistrationEntry]
    :param general_ledger_entries:
    :type general_ledger_entries:
     list[~azure.mgmt.devtestlabs.models.GeneralLedgerEntry]
    :param currencies:
    :type currencies: list[~azure.mgmt.devtestlabs.models.Currency]
    :param payment_methods:
    :type payment_methods: list[~azure.mgmt.devtestlabs.models.PaymentMethod]
    :param dimensions:
    :type dimensions: list[~azure.mgmt.devtestlabs.models.Dimension]
    :param dimension_values:
    :type dimension_values:
     list[~azure.mgmt.devtestlabs.models.DimensionValue]
    :param dimension_lines:
    :type dimension_lines: list[~azure.mgmt.devtestlabs.models.DimensionLine]
    :param payment_terms:
    :type payment_terms: list[~azure.mgmt.devtestlabs.models.PaymentTerm]
    :param shipment_methods:
    :type shipment_methods:
     list[~azure.mgmt.devtestlabs.models.ShipmentMethod]
    :param item_categories:
    :type item_categories: list[~azure.mgmt.devtestlabs.models.ItemCategory]
    :param cash_flow_statement:
    :type cash_flow_statement:
     list[~azure.mgmt.devtestlabs.models.CashFlowStatement]
    :param countries_regions:
    :type countries_regions:
     list[~azure.mgmt.devtestlabs.models.CountryRegion]
    :param sales_orders:
    :type sales_orders: list[~azure.mgmt.devtestlabs.models.SalesOrder]
    :param sales_order_lines:
    :type sales_order_lines:
     list[~azure.mgmt.devtestlabs.models.SalesOrderLine]
    :param retained_earnings_statement:
    :type retained_earnings_statement:
     list[~azure.mgmt.devtestlabs.models.RetainedEarningsStatement]
    :param units_of_measure:
    :type units_of_measure: list[~azure.mgmt.devtestlabs.models.UnitOfMeasure]
    :param aged_accounts_receivable:
    :type aged_accounts_receivable:
     list[~azure.mgmt.devtestlabs.models.AgedAccountsReceivable]
    :param aged_accounts_payable:
    :type aged_accounts_payable:
     list[~azure.mgmt.devtestlabs.models.AgedAccountsPayable]
    :param balance_sheet:
    :type balance_sheet: list[~azure.mgmt.devtestlabs.models.BalanceSheet]
    :param trial_balance:
    :type trial_balance: list[~azure.mgmt.devtestlabs.models.TrialBalance]
    :param income_statement:
    :type income_statement:
     list[~azure.mgmt.devtestlabs.models.IncomeStatement]
    :param tax_areas:
    :type tax_areas: list[~azure.mgmt.devtestlabs.models.TaxArea]
    :param sales_quotes:
    :type sales_quotes: list[~azure.mgmt.devtestlabs.models.SalesQuote]
    :param sales_quote_lines:
    :type sales_quote_lines:
     list[~azure.mgmt.devtestlabs.models.SalesQuoteLine]
    :param sales_credit_memos:
    :type sales_credit_memos:
     list[~azure.mgmt.devtestlabs.models.SalesCreditMemo]
    :param sales_credit_memo_lines:
    :type sales_credit_memo_lines:
     list[~azure.mgmt.devtestlabs.models.SalesCreditMemoLine]
    :param general_ledger_entry_attachments:
    :type general_ledger_entry_attachments:
     list[~azure.mgmt.devtestlabs.models.GeneralLedgerEntryAttachments]
    :param purchase_invoices:
    :type purchase_invoices:
     list[~azure.mgmt.devtestlabs.models.PurchaseInvoice]
    :param purchase_invoice_lines:
    :type purchase_invoice_lines:
     list[~azure.mgmt.devtestlabs.models.PurchaseInvoiceLine]
    :param customer_sales:
    :type customer_sales: list[~azure.mgmt.devtestlabs.models.CustomerSale]
    :param vendor_purchases:
    :type vendor_purchases:
     list[~azure.mgmt.devtestlabs.models.VendorPurchase]
    """

    _validation = {
        'name': {'max_length': 30},
        'display_name': {'max_length': 250},
        'business_profile_id': {'max_length': 250},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'system_version': {'key': 'systemVersion', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'display_name': {'key': 'displayName', 'type': 'str'},
        'business_profile_id': {'key': 'businessProfileId', 'type': 'str'},
        'items': {'key': 'items', 'type': '[Item]'},
        'picture': {'key': 'picture', 'type': '[Picture]'},
        'default_dimensions': {'key': 'defaultDimensions', 'type': '[DefaultDimensions]'},
        'customers': {'key': 'customers', 'type': '[Customer]'},
        'customer_financial_details': {'key': 'customerFinancialDetails', 'type': '[CustomerFinancialDetail]'},
        'vendors': {'key': 'vendors', 'type': '[Vendor]'},
        'company_information': {'key': 'companyInformation', 'type': '[CompanyInformation]'},
        'sales_invoices': {'key': 'salesInvoices', 'type': '[SalesInvoice]'},
        'sales_invoice_lines': {'key': 'salesInvoiceLines', 'type': '[SalesInvoiceLine]'},
        'pdf_document': {'key': 'pdfDocument', 'type': '[PdfDocument]'},
        'customer_payment_journals': {'key': 'customerPaymentJournals', 'type': '[CustomerPaymentJournal]'},
        'customer_payments': {'key': 'customerPayments', 'type': '[CustomerPayment]'},
        'accounts': {'key': 'accounts', 'type': '[Account]'},
        'tax_groups': {'key': 'taxGroups', 'type': '[TaxGroup]'},
        'journals': {'key': 'journals', 'type': '[Journal]'},
        'journal_lines': {'key': 'journalLines', 'type': '[JournalLine]'},
        'attachments': {'key': 'attachments', 'type': '[Attachments]'},
        'employees': {'key': 'employees', 'type': '[Employee]'},
        'time_registration_entries': {'key': 'timeRegistrationEntries', 'type': '[TimeRegistrationEntry]'},
        'general_ledger_entries': {'key': 'generalLedgerEntries', 'type': '[GeneralLedgerEntry]'},
        'currencies': {'key': 'currencies', 'type': '[Currency]'},
        'payment_methods': {'key': 'paymentMethods', 'type': '[PaymentMethod]'},
        'dimensions': {'key': 'dimensions', 'type': '[Dimension]'},
        'dimension_values': {'key': 'dimensionValues', 'type': '[DimensionValue]'},
        'dimension_lines': {'key': 'dimensionLines', 'type': '[DimensionLine]'},
        'payment_terms': {'key': 'paymentTerms', 'type': '[PaymentTerm]'},
        'shipment_methods': {'key': 'shipmentMethods', 'type': '[ShipmentMethod]'},
        'item_categories': {'key': 'itemCategories', 'type': '[ItemCategory]'},
        'cash_flow_statement': {'key': 'cashFlowStatement', 'type': '[CashFlowStatement]'},
        'countries_regions': {'key': 'countriesRegions', 'type': '[CountryRegion]'},
        'sales_orders': {'key': 'salesOrders', 'type': '[SalesOrder]'},
        'sales_order_lines': {'key': 'salesOrderLines', 'type': '[SalesOrderLine]'},
        'retained_earnings_statement': {'key': 'retainedEarningsStatement', 'type': '[RetainedEarningsStatement]'},
        'units_of_measure': {'key': 'unitsOfMeasure', 'type': '[UnitOfMeasure]'},
        'aged_accounts_receivable': {'key': 'agedAccountsReceivable', 'type': '[AgedAccountsReceivable]'},
        'aged_accounts_payable': {'key': 'agedAccountsPayable', 'type': '[AgedAccountsPayable]'},
        'balance_sheet': {'key': 'balanceSheet', 'type': '[BalanceSheet]'},
        'trial_balance': {'key': 'trialBalance', 'type': '[TrialBalance]'},
        'income_statement': {'key': 'incomeStatement', 'type': '[IncomeStatement]'},
        'tax_areas': {'key': 'taxAreas', 'type': '[TaxArea]'},
        'sales_quotes': {'key': 'salesQuotes', 'type': '[SalesQuote]'},
        'sales_quote_lines': {'key': 'salesQuoteLines', 'type': '[SalesQuoteLine]'},
        'sales_credit_memos': {'key': 'salesCreditMemos', 'type': '[SalesCreditMemo]'},
        'sales_credit_memo_lines': {'key': 'salesCreditMemoLines', 'type': '[SalesCreditMemoLine]'},
        'general_ledger_entry_attachments': {'key': 'generalLedgerEntryAttachments', 'type': '[GeneralLedgerEntryAttachments]'},
        'purchase_invoices': {'key': 'purchaseInvoices', 'type': '[PurchaseInvoice]'},
        'purchase_invoice_lines': {'key': 'purchaseInvoiceLines', 'type': '[PurchaseInvoiceLine]'},
        'customer_sales': {'key': 'customerSales', 'type': '[CustomerSale]'},
        'vendor_purchases': {'key': 'vendorPurchases', 'type': '[VendorPurchase]'},
    }

    def __init__(self, *, id: str=None, system_version: str=None, name: str=None, display_name: str=None, business_profile_id: str=None, items=None, picture=None, default_dimensions=None, customers=None, customer_financial_details=None, vendors=None, company_information=None, sales_invoices=None, sales_invoice_lines=None, pdf_document=None, customer_payment_journals=None, customer_payments=None, accounts=None, tax_groups=None, journals=None, journal_lines=None, attachments=None, employees=None, time_registration_entries=None, general_ledger_entries=None, currencies=None, payment_methods=None, dimensions=None, dimension_values=None, dimension_lines=None, payment_terms=None, shipment_methods=None, item_categories=None, cash_flow_statement=None, countries_regions=None, sales_orders=None, sales_order_lines=None, retained_earnings_statement=None, units_of_measure=None, aged_accounts_receivable=None, aged_accounts_payable=None, balance_sheet=None, trial_balance=None, income_statement=None, tax_areas=None, sales_quotes=None, sales_quote_lines=None, sales_credit_memos=None, sales_credit_memo_lines=None, general_ledger_entry_attachments=None, purchase_invoices=None, purchase_invoice_lines=None, customer_sales=None, vendor_purchases=None, **kwargs) -> None:
        super(Company, self).__init__(**kwargs)
        self.id = id
        self.system_version = system_version
        self.name = name
        self.display_name = display_name
        self.business_profile_id = business_profile_id
        self.items = items
        self.picture = picture
        self.default_dimensions = default_dimensions
        self.customers = customers
        self.customer_financial_details = customer_financial_details
        self.vendors = vendors
        self.company_information = company_information
        self.sales_invoices = sales_invoices
        self.sales_invoice_lines = sales_invoice_lines
        self.pdf_document = pdf_document
        self.customer_payment_journals = customer_payment_journals
        self.customer_payments = customer_payments
        self.accounts = accounts
        self.tax_groups = tax_groups
        self.journals = journals
        self.journal_lines = journal_lines
        self.attachments = attachments
        self.employees = employees
        self.time_registration_entries = time_registration_entries
        self.general_ledger_entries = general_ledger_entries
        self.currencies = currencies
        self.payment_methods = payment_methods
        self.dimensions = dimensions
        self.dimension_values = dimension_values
        self.dimension_lines = dimension_lines
        self.payment_terms = payment_terms
        self.shipment_methods = shipment_methods
        self.item_categories = item_categories
        self.cash_flow_statement = cash_flow_statement
        self.countries_regions = countries_regions
        self.sales_orders = sales_orders
        self.sales_order_lines = sales_order_lines
        self.retained_earnings_statement = retained_earnings_statement
        self.units_of_measure = units_of_measure
        self.aged_accounts_receivable = aged_accounts_receivable
        self.aged_accounts_payable = aged_accounts_payable
        self.balance_sheet = balance_sheet
        self.trial_balance = trial_balance
        self.income_statement = income_statement
        self.tax_areas = tax_areas
        self.sales_quotes = sales_quotes
        self.sales_quote_lines = sales_quote_lines
        self.sales_credit_memos = sales_credit_memos
        self.sales_credit_memo_lines = sales_credit_memo_lines
        self.general_ledger_entry_attachments = general_ledger_entry_attachments
        self.purchase_invoices = purchase_invoices
        self.purchase_invoice_lines = purchase_invoice_lines
        self.customer_sales = customer_sales
        self.vendor_purchases = vendor_purchases
