# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class CustomerSale(Model):
    """CustomerSale.

    :param customer_id: The customerId property for the customerSale entity
    :type customer_id: str
    :param customer_number: The customerNumber property for the customerSale
     entity
    :type customer_number: str
    :param name: The name property for the customerSale entity
    :type name: str
    :param total_sales_amount: The totalSalesAmount property for the
     customerSale entity
    :type total_sales_amount: decimal.Decimal
    :param date_filter_filter_only: The dateFilter_FilterOnly property for the
     customerSale entity
    :type date_filter_filter_only: datetime
    """

    _validation = {
        'customer_number': {'max_length': 20},
        'name': {'max_length': 100},
    }

    _attribute_map = {
        'customer_id': {'key': 'customerId', 'type': 'str'},
        'customer_number': {'key': 'customerNumber', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'total_sales_amount': {'key': 'totalSalesAmount', 'type': 'decimal'},
        'date_filter_filter_only': {'key': 'dateFilter_FilterOnly', 'type': 'iso-8601'},
    }

    def __init__(self, *, customer_id: str=None, customer_number: str=None, name: str=None, total_sales_amount=None, date_filter_filter_only=None, **kwargs) -> None:
        super(CustomerSale, self).__init__(**kwargs)
        self.customer_id = customer_id
        self.customer_number = customer_number
        self.name = name
        self.total_sales_amount = total_sales_amount
        self.date_filter_filter_only = date_filter_filter_only
