# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class CustomerPayment(Model):
    """CustomerPayment.

    :param id: The id property for the customerPayment entity
    :type id: str
    :param journal_display_name: The journalDisplayName property for the
     customerPayment entity
    :type journal_display_name: str
    :param line_number: The lineNumber property for the customerPayment entity
    :type line_number: int
    :param customer_id: The customerId property for the customerPayment entity
    :type customer_id: str
    :param customer_number: The customerNumber property for the
     customerPayment entity
    :type customer_number: str
    :param contact_id: The contactId property for the customerPayment entity
    :type contact_id: str
    :param posting_date: The postingDate property for the customerPayment
     entity
    :type posting_date: datetime
    :param document_number: The documentNumber property for the
     customerPayment entity
    :type document_number: str
    :param external_document_number: The externalDocumentNumber property for
     the customerPayment entity
    :type external_document_number: str
    :param amount: The amount property for the customerPayment entity
    :type amount: decimal.Decimal
    :param applies_to_invoice_id: The appliesToInvoiceId property for the
     customerPayment entity
    :type applies_to_invoice_id: str
    :param applies_to_invoice_number: The appliesToInvoiceNumber property for
     the customerPayment entity
    :type applies_to_invoice_number: str
    :param description: The description property for the customerPayment
     entity
    :type description: str
    :param comment: The comment property for the customerPayment entity
    :type comment: str
    :param dimensions:
    :type dimensions: list[~azure.mgmt.devtestlabs.models.Dimensiontype]
    :param last_modified_date_time: The lastModifiedDateTime property for the
     customerPayment entity
    :type last_modified_date_time: datetime
    :param customer:
    :type customer: ~azure.mgmt.devtestlabs.models.Customer
    """

    _validation = {
        'customer_number': {'max_length': 20},
        'contact_id': {'max_length': 250},
        'document_number': {'max_length': 20},
        'external_document_number': {'max_length': 35},
        'description': {'max_length': 100},
        'comment': {'max_length': 250},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'journal_display_name': {'key': 'journalDisplayName', 'type': 'str'},
        'line_number': {'key': 'lineNumber', 'type': 'int'},
        'customer_id': {'key': 'customerId', 'type': 'str'},
        'customer_number': {'key': 'customerNumber', 'type': 'str'},
        'contact_id': {'key': 'contactId', 'type': 'str'},
        'posting_date': {'key': 'postingDate', 'type': 'iso-8601'},
        'document_number': {'key': 'documentNumber', 'type': 'str'},
        'external_document_number': {'key': 'externalDocumentNumber', 'type': 'str'},
        'amount': {'key': 'amount', 'type': 'decimal'},
        'applies_to_invoice_id': {'key': 'appliesToInvoiceId', 'type': 'str'},
        'applies_to_invoice_number': {'key': 'appliesToInvoiceNumber', 'type': 'str'},
        'description': {'key': 'description', 'type': 'str'},
        'comment': {'key': 'comment', 'type': 'str'},
        'dimensions': {'key': 'dimensions', 'type': '[Dimensiontype]'},
        'last_modified_date_time': {'key': 'lastModifiedDateTime', 'type': 'iso-8601'},
        'customer': {'key': 'customer', 'type': 'Customer'},
    }

    def __init__(self, **kwargs):
        super(CustomerPayment, self).__init__(**kwargs)
        self.id = kwargs.get('id', None)
        self.journal_display_name = kwargs.get('journal_display_name', None)
        self.line_number = kwargs.get('line_number', None)
        self.customer_id = kwargs.get('customer_id', None)
        self.customer_number = kwargs.get('customer_number', None)
        self.contact_id = kwargs.get('contact_id', None)
        self.posting_date = kwargs.get('posting_date', None)
        self.document_number = kwargs.get('document_number', None)
        self.external_document_number = kwargs.get('external_document_number', None)
        self.amount = kwargs.get('amount', None)
        self.applies_to_invoice_id = kwargs.get('applies_to_invoice_id', None)
        self.applies_to_invoice_number = kwargs.get('applies_to_invoice_number', None)
        self.description = kwargs.get('description', None)
        self.comment = kwargs.get('comment', None)
        self.dimensions = kwargs.get('dimensions', None)
        self.last_modified_date_time = kwargs.get('last_modified_date_time', None)
        self.customer = kwargs.get('customer', None)
