# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class CustomerPaymentJournal(Model):
    """CustomerPaymentJournal.

    :param id: The id property for the customerPaymentJournal entity
    :type id: str
    :param code: The code property for the customerPaymentJournal entity
    :type code: str
    :param display_name: The displayName property for the
     customerPaymentJournal entity
    :type display_name: str
    :param last_modified_date_time: The lastModifiedDateTime property for the
     customerPaymentJournal entity
    :type last_modified_date_time: datetime
    :param balancing_account_id: The balancingAccountId property for the
     customerPaymentJournal entity
    :type balancing_account_id: str
    :param balancing_account_number: The balancingAccountNumber property for
     the customerPaymentJournal entity
    :type balancing_account_number: str
    :param customer_payments:
    :type customer_payments:
     list[~azure.mgmt.devtestlabs.models.CustomerPayment]
    :param account:
    :type account: ~azure.mgmt.devtestlabs.models.Account
    """

    _validation = {
        'code': {'max_length': 10},
        'display_name': {'max_length': 100},
        'balancing_account_number': {'max_length': 20},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'code': {'key': 'code', 'type': 'str'},
        'display_name': {'key': 'displayName', 'type': 'str'},
        'last_modified_date_time': {'key': 'lastModifiedDateTime', 'type': 'iso-8601'},
        'balancing_account_id': {'key': 'balancingAccountId', 'type': 'str'},
        'balancing_account_number': {'key': 'balancingAccountNumber', 'type': 'str'},
        'customer_payments': {'key': 'customerPayments', 'type': '[CustomerPayment]'},
        'account': {'key': 'account', 'type': 'Account'},
    }

    def __init__(self, *, id: str=None, code: str=None, display_name: str=None, last_modified_date_time=None, balancing_account_id: str=None, balancing_account_number: str=None, customer_payments=None, account=None, **kwargs) -> None:
        super(CustomerPaymentJournal, self).__init__(**kwargs)
        self.id = id
        self.code = code
        self.display_name = display_name
        self.last_modified_date_time = last_modified_date_time
        self.balancing_account_id = balancing_account_id
        self.balancing_account_number = balancing_account_number
        self.customer_payments = customer_payments
        self.account = account
