# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class CustomerFinancialDetail(Model):
    """CustomerFinancialDetail.

    :param id: The id property for the customerFinancialDetail entity
    :type id: str
    :param number: The number property for the customerFinancialDetail entity
    :type number: str
    :param balance: The balance property for the customerFinancialDetail
     entity
    :type balance: decimal.Decimal
    :param total_sales_excluding_tax: The totalSalesExcludingTax property for
     the customerFinancialDetail entity
    :type total_sales_excluding_tax: decimal.Decimal
    :param overdue_amount: The overdueAmount property for the
     customerFinancialDetail entity
    :type overdue_amount: decimal.Decimal
    """

    _validation = {
        'number': {'max_length': 20},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'number': {'key': 'number', 'type': 'str'},
        'balance': {'key': 'balance', 'type': 'decimal'},
        'total_sales_excluding_tax': {'key': 'totalSalesExcludingTax', 'type': 'decimal'},
        'overdue_amount': {'key': 'overdueAmount', 'type': 'decimal'},
    }

    def __init__(self, **kwargs):
        super(CustomerFinancialDetail, self).__init__(**kwargs)
        self.id = kwargs.get('id', None)
        self.number = kwargs.get('number', None)
        self.balance = kwargs.get('balance', None)
        self.total_sales_excluding_tax = kwargs.get('total_sales_excluding_tax', None)
        self.overdue_amount = kwargs.get('overdue_amount', None)
