# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class CustomerPayment(Model):
    """CustomerPayment.

    :param id: The id property for the customerPayment entity
    :type id: str
    :param journal_display_name: The journalDisplayName property for the
     customerPayment entity
    :type journal_display_name: str
    :param line_number: The lineNumber property for the customerPayment entity
    :type line_number: int
    :param customer_id: The customerId property for the customerPayment entity
    :type customer_id: str
    :param customer_number: The customerNumber property for the
     customerPayment entity
    :type customer_number: str
    :param contact_id: The contactId property for the customerPayment entity
    :type contact_id: str
    :param posting_date: The postingDate property for the customerPayment
     entity
    :type posting_date: datetime
    :param document_number: The documentNumber property for the
     customerPayment entity
    :type document_number: str
    :param external_document_number: The externalDocumentNumber property for
     the customerPayment entity
    :type external_document_number: str
    :param amount: The amount property for the customerPayment entity
    :type amount: decimal.Decimal
    :param applies_to_invoice_id: The appliesToInvoiceId property for the
     customerPayment entity
    :type applies_to_invoice_id: str
    :param applies_to_invoice_number: The appliesToInvoiceNumber property for
     the customerPayment entity
    :type applies_to_invoice_number: str
    :param description: The description property for the customerPayment
     entity
    :type description: str
    :param comment: The comment property for the customerPayment entity
    :type comment: str
    :param dimensions:
    :type dimensions: list[~azure.mgmt.devtestlabs.models.Dimensiontype]
    :param last_modified_date_time: The lastModifiedDateTime property for the
     customerPayment entity
    :type last_modified_date_time: datetime
    :param customer:
    :type customer: ~azure.mgmt.devtestlabs.models.Customer
    """

    _validation = {
        'customer_number': {'max_length': 20},
        'contact_id': {'max_length': 250},
        'document_number': {'max_length': 20},
        'external_document_number': {'max_length': 35},
        'description': {'max_length': 100},
        'comment': {'max_length': 250},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'journal_display_name': {'key': 'journalDisplayName', 'type': 'str'},
        'line_number': {'key': 'lineNumber', 'type': 'int'},
        'customer_id': {'key': 'customerId', 'type': 'str'},
        'customer_number': {'key': 'customerNumber', 'type': 'str'},
        'contact_id': {'key': 'contactId', 'type': 'str'},
        'posting_date': {'key': 'postingDate', 'type': 'iso-8601'},
        'document_number': {'key': 'documentNumber', 'type': 'str'},
        'external_document_number': {'key': 'externalDocumentNumber', 'type': 'str'},
        'amount': {'key': 'amount', 'type': 'decimal'},
        'applies_to_invoice_id': {'key': 'appliesToInvoiceId', 'type': 'str'},
        'applies_to_invoice_number': {'key': 'appliesToInvoiceNumber', 'type': 'str'},
        'description': {'key': 'description', 'type': 'str'},
        'comment': {'key': 'comment', 'type': 'str'},
        'dimensions': {'key': 'dimensions', 'type': '[Dimensiontype]'},
        'last_modified_date_time': {'key': 'lastModifiedDateTime', 'type': 'iso-8601'},
        'customer': {'key': 'customer', 'type': 'Customer'},
    }

    def __init__(self, *, id: str=None, journal_display_name: str=None, line_number: int=None, customer_id: str=None, customer_number: str=None, contact_id: str=None, posting_date=None, document_number: str=None, external_document_number: str=None, amount=None, applies_to_invoice_id: str=None, applies_to_invoice_number: str=None, description: str=None, comment: str=None, dimensions=None, last_modified_date_time=None, customer=None, **kwargs) -> None:
        super(CustomerPayment, self).__init__(**kwargs)
        self.id = id
        self.journal_display_name = journal_display_name
        self.line_number = line_number
        self.customer_id = customer_id
        self.customer_number = customer_number
        self.contact_id = contact_id
        self.posting_date = posting_date
        self.document_number = document_number
        self.external_document_number = external_document_number
        self.amount = amount
        self.applies_to_invoice_id = applies_to_invoice_id
        self.applies_to_invoice_number = applies_to_invoice_number
        self.description = description
        self.comment = comment
        self.dimensions = dimensions
        self.last_modified_date_time = last_modified_date_time
        self.customer = customer
