# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class DefaultDimensions(Model):
    """DefaultDimensions.

    :param parent_id: The parentId property for the defaultDimensions entity
    :type parent_id: str
    :param dimension_id: The dimensionId property for the defaultDimensions
     entity
    :type dimension_id: str
    :param dimension_code: The dimensionCode property for the
     defaultDimensions entity
    :type dimension_code: str
    :param dimension_value_id: The dimensionValueId property for the
     defaultDimensions entity
    :type dimension_value_id: str
    :param dimension_value_code: The dimensionValueCode property for the
     defaultDimensions entity
    :type dimension_value_code: str
    :param posting_validation: The postingValidation property for the
     defaultDimensions entity
    :type posting_validation: str
    :param account:
    :type account: ~azure.mgmt.devtestlabs.models.Account
    :param dimension:
    :type dimension: ~azure.mgmt.devtestlabs.models.Dimension
    :param dimension_value:
    :type dimension_value: ~azure.mgmt.devtestlabs.models.DimensionValue
    """

    _validation = {
        'dimension_code': {'max_length': 20},
        'dimension_value_code': {'max_length': 20},
    }

    _attribute_map = {
        'parent_id': {'key': 'parentId', 'type': 'str'},
        'dimension_id': {'key': 'dimensionId', 'type': 'str'},
        'dimension_code': {'key': 'dimensionCode', 'type': 'str'},
        'dimension_value_id': {'key': 'dimensionValueId', 'type': 'str'},
        'dimension_value_code': {'key': 'dimensionValueCode', 'type': 'str'},
        'posting_validation': {'key': 'postingValidation', 'type': 'str'},
        'account': {'key': 'account', 'type': 'Account'},
        'dimension': {'key': 'dimension', 'type': 'Dimension'},
        'dimension_value': {'key': 'dimensionValue', 'type': 'DimensionValue'},
    }

    def __init__(self, *, parent_id: str=None, dimension_id: str=None, dimension_code: str=None, dimension_value_id: str=None, dimension_value_code: str=None, posting_validation: str=None, account=None, dimension=None, dimension_value=None, **kwargs) -> None:
        super(DefaultDimensions, self).__init__(**kwargs)
        self.parent_id = parent_id
        self.dimension_id = dimension_id
        self.dimension_code = dimension_code
        self.dimension_value_id = dimension_value_id
        self.dimension_value_code = dimension_value_code
        self.posting_validation = posting_validation
        self.account = account
        self.dimension = dimension
        self.dimension_value = dimension_value
