# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class Dimensiontype(Model):
    """Dimensiontype.

    :param code: The code property for the dimensiontype entity
    :type code: str
    :param display_name: The displayName property for the dimensiontype entity
    :type display_name: str
    :param value_code: The valueCode property for the dimensiontype entity
    :type value_code: str
    :param value_display_name: The valueDisplayName property for the
     dimensiontype entity
    :type value_display_name: str
    :param customer:
    :type customer: ~azure.mgmt.devtestlabs.models.Customer
    """

    _attribute_map = {
        'code': {'key': 'code', 'type': 'str'},
        'display_name': {'key': 'displayName', 'type': 'str'},
        'value_code': {'key': 'valueCode', 'type': 'str'},
        'value_display_name': {'key': 'valueDisplayName', 'type': 'str'},
        'customer': {'key': 'customer', 'type': 'Customer'},
    }

    def __init__(self, *, code: str=None, display_name: str=None, value_code: str=None, value_display_name: str=None, customer=None, **kwargs) -> None:
        super(Dimensiontype, self).__init__(**kwargs)
        self.code = code
        self.display_name = display_name
        self.value_code = value_code
        self.value_display_name = value_display_name
        self.customer = customer
