# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class Dimension(Model):
    """Dimension.

    :param id: The id property for the dimension entity
    :type id: str
    :param code: The code property for the dimension entity
    :type code: str
    :param display_name: The displayName property for the dimension entity
    :type display_name: str
    :param last_modified_date_time: The lastModifiedDateTime property for the
     dimension entity
    :type last_modified_date_time: datetime
    :param dimension_values:
    :type dimension_values:
     list[~azure.mgmt.devtestlabs.models.DimensionValue]
    """

    _validation = {
        'code': {'max_length': 20},
        'display_name': {'max_length': 30},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'code': {'key': 'code', 'type': 'str'},
        'display_name': {'key': 'displayName', 'type': 'str'},
        'last_modified_date_time': {'key': 'lastModifiedDateTime', 'type': 'iso-8601'},
        'dimension_values': {'key': 'dimensionValues', 'type': '[DimensionValue]'},
    }

    def __init__(self, *, id: str=None, code: str=None, display_name: str=None, last_modified_date_time=None, dimension_values=None, **kwargs) -> None:
        super(Dimension, self).__init__(**kwargs)
        self.id = id
        self.code = code
        self.display_name = display_name
        self.last_modified_date_time = last_modified_date_time
        self.dimension_values = dimension_values
