# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class DimensionLine(Model):
    """DimensionLine.

    :param parent_id: The parentId property for the dimensionLine entity
    :type parent_id: str
    :param id: The id property for the dimensionLine entity
    :type id: str
    :param code: The code property for the dimensionLine entity
    :type code: str
    :param display_name: The displayName property for the dimensionLine entity
    :type display_name: str
    :param value_id: The valueId property for the dimensionLine entity
    :type value_id: str
    :param value_code: The valueCode property for the dimensionLine entity
    :type value_code: str
    :param value_display_name: The valueDisplayName property for the
     dimensionLine entity
    :type value_display_name: str
    :param dimension:
    :type dimension: ~azure.mgmt.devtestlabs.models.Dimension
    """

    _validation = {
        'code': {'max_length': 20},
        'display_name': {'max_length': 30},
        'value_display_name': {'max_length': 50},
    }

    _attribute_map = {
        'parent_id': {'key': 'parentId', 'type': 'str'},
        'id': {'key': 'id', 'type': 'str'},
        'code': {'key': 'code', 'type': 'str'},
        'display_name': {'key': 'displayName', 'type': 'str'},
        'value_id': {'key': 'valueId', 'type': 'str'},
        'value_code': {'key': 'valueCode', 'type': 'str'},
        'value_display_name': {'key': 'valueDisplayName', 'type': 'str'},
        'dimension': {'key': 'dimension', 'type': 'Dimension'},
    }

    def __init__(self, *, parent_id: str=None, id: str=None, code: str=None, display_name: str=None, value_id: str=None, value_code: str=None, value_display_name: str=None, dimension=None, **kwargs) -> None:
        super(DimensionLine, self).__init__(**kwargs)
        self.parent_id = parent_id
        self.id = id
        self.code = code
        self.display_name = display_name
        self.value_id = value_id
        self.value_code = value_code
        self.value_display_name = value_display_name
        self.dimension = dimension
