# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class Dimensiontype(Model):
    """Dimensiontype.

    :param code: The code property for the dimensiontype entity
    :type code: str
    :param display_name: The displayName property for the dimensiontype entity
    :type display_name: str
    :param value_code: The valueCode property for the dimensiontype entity
    :type value_code: str
    :param value_display_name: The valueDisplayName property for the
     dimensiontype entity
    :type value_display_name: str
    :param customer:
    :type customer: ~azure.mgmt.devtestlabs.models.Customer
    """

    _attribute_map = {
        'code': {'key': 'code', 'type': 'str'},
        'display_name': {'key': 'displayName', 'type': 'str'},
        'value_code': {'key': 'valueCode', 'type': 'str'},
        'value_display_name': {'key': 'valueDisplayName', 'type': 'str'},
        'customer': {'key': 'customer', 'type': 'Customer'},
    }

    def __init__(self, **kwargs):
        super(Dimensiontype, self).__init__(**kwargs)
        self.code = kwargs.get('code', None)
        self.display_name = kwargs.get('display_name', None)
        self.value_code = kwargs.get('value_code', None)
        self.value_display_name = kwargs.get('value_display_name', None)
        self.customer = kwargs.get('customer', None)
