# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class Documentlineobjectdetailstype(Model):
    """Documentlineobjectdetailstype.

    :param number: The number property for the documentlineobjectdetailstype
     entity
    :type number: str
    :param display_name: The displayName property for the
     documentlineobjectdetailstype entity
    :type display_name: str
    :param item:
    :type item: ~azure.mgmt.devtestlabs.models.Item
    :param account:
    :type account: ~azure.mgmt.devtestlabs.models.Account
    """

    _validation = {
        'number': {'max_length': 20},
        'display_name': {'max_length': 100},
    }

    _attribute_map = {
        'number': {'key': 'number', 'type': 'str'},
        'display_name': {'key': 'displayName', 'type': 'str'},
        'item': {'key': 'item', 'type': 'Item'},
        'account': {'key': 'account', 'type': 'Account'},
    }

    def __init__(self, **kwargs):
        super(Documentlineobjectdetailstype, self).__init__(**kwargs)
        self.number = kwargs.get('number', None)
        self.display_name = kwargs.get('display_name', None)
        self.item = kwargs.get('item', None)
        self.account = kwargs.get('account', None)
