# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class Employee(Model):
    """Employee.

    :param id: The id property for the employee entity
    :type id: str
    :param number: The number property for the employee entity
    :type number: str
    :param display_name: The displayName property for the employee entity
    :type display_name: str
    :param given_name: The givenName property for the employee entity
    :type given_name: str
    :param middle_name: The middleName property for the employee entity
    :type middle_name: str
    :param surname: The surname property for the employee entity
    :type surname: str
    :param job_title: The jobTitle property for the employee entity
    :type job_title: str
    :param address:
    :type address: ~azure.mgmt.devtestlabs.models.Postaladdresstype
    :param phone_number: The phoneNumber property for the employee entity
    :type phone_number: str
    :param mobile_phone: The mobilePhone property for the employee entity
    :type mobile_phone: str
    :param email: The email property for the employee entity
    :type email: str
    :param personal_email: The personalEmail property for the employee entity
    :type personal_email: str
    :param employment_date: The employmentDate property for the employee
     entity
    :type employment_date: datetime
    :param termination_date: The terminationDate property for the employee
     entity
    :type termination_date: datetime
    :param status: The status property for the employee entity
    :type status: str
    :param birth_date: The birthDate property for the employee entity
    :type birth_date: datetime
    :param statistics_group_code: The statisticsGroupCode property for the
     employee entity
    :type statistics_group_code: str
    :param last_modified_date_time: The lastModifiedDateTime property for the
     employee entity
    :type last_modified_date_time: datetime
    :param picture:
    :type picture: list[~azure.mgmt.devtestlabs.models.Picture]
    :param default_dimensions:
    :type default_dimensions:
     list[~azure.mgmt.devtestlabs.models.DefaultDimensions]
    :param time_registration_entries:
    :type time_registration_entries:
     list[~azure.mgmt.devtestlabs.models.TimeRegistrationEntry]
    """

    _validation = {
        'number': {'max_length': 20},
        'given_name': {'max_length': 30},
        'middle_name': {'max_length': 30},
        'surname': {'max_length': 30},
        'job_title': {'max_length': 30},
        'phone_number': {'max_length': 30},
        'mobile_phone': {'max_length': 30},
        'email': {'max_length': 80},
        'personal_email': {'max_length': 80},
        'statistics_group_code': {'max_length': 10},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'number': {'key': 'number', 'type': 'str'},
        'display_name': {'key': 'displayName', 'type': 'str'},
        'given_name': {'key': 'givenName', 'type': 'str'},
        'middle_name': {'key': 'middleName', 'type': 'str'},
        'surname': {'key': 'surname', 'type': 'str'},
        'job_title': {'key': 'jobTitle', 'type': 'str'},
        'address': {'key': 'address', 'type': 'Postaladdresstype'},
        'phone_number': {'key': 'phoneNumber', 'type': 'str'},
        'mobile_phone': {'key': 'mobilePhone', 'type': 'str'},
        'email': {'key': 'email', 'type': 'str'},
        'personal_email': {'key': 'personalEmail', 'type': 'str'},
        'employment_date': {'key': 'employmentDate', 'type': 'iso-8601'},
        'termination_date': {'key': 'terminationDate', 'type': 'iso-8601'},
        'status': {'key': 'status', 'type': 'str'},
        'birth_date': {'key': 'birthDate', 'type': 'iso-8601'},
        'statistics_group_code': {'key': 'statisticsGroupCode', 'type': 'str'},
        'last_modified_date_time': {'key': 'lastModifiedDateTime', 'type': 'iso-8601'},
        'picture': {'key': 'picture', 'type': '[Picture]'},
        'default_dimensions': {'key': 'defaultDimensions', 'type': '[DefaultDimensions]'},
        'time_registration_entries': {'key': 'timeRegistrationEntries', 'type': '[TimeRegistrationEntry]'},
    }

    def __init__(self, **kwargs):
        super(Employee, self).__init__(**kwargs)
        self.id = kwargs.get('id', None)
        self.number = kwargs.get('number', None)
        self.display_name = kwargs.get('display_name', None)
        self.given_name = kwargs.get('given_name', None)
        self.middle_name = kwargs.get('middle_name', None)
        self.surname = kwargs.get('surname', None)
        self.job_title = kwargs.get('job_title', None)
        self.address = kwargs.get('address', None)
        self.phone_number = kwargs.get('phone_number', None)
        self.mobile_phone = kwargs.get('mobile_phone', None)
        self.email = kwargs.get('email', None)
        self.personal_email = kwargs.get('personal_email', None)
        self.employment_date = kwargs.get('employment_date', None)
        self.termination_date = kwargs.get('termination_date', None)
        self.status = kwargs.get('status', None)
        self.birth_date = kwargs.get('birth_date', None)
        self.statistics_group_code = kwargs.get('statistics_group_code', None)
        self.last_modified_date_time = kwargs.get('last_modified_date_time', None)
        self.picture = kwargs.get('picture', None)
        self.default_dimensions = kwargs.get('default_dimensions', None)
        self.time_registration_entries = kwargs.get('time_registration_entries', None)
