# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class GeneralLedgerEntryAttachments(Model):
    """GeneralLedgerEntryAttachments.

    :param general_ledger_entry_number: The generalLedgerEntryNumber property
     for the generalLedgerEntryAttachments entity
    :type general_ledger_entry_number: int
    :param id: The id property for the generalLedgerEntryAttachments entity
    :type id: str
    :param file_name: The fileName property for the
     generalLedgerEntryAttachments entity
    :type file_name: str
    :param byte_size: The byteSize property for the
     generalLedgerEntryAttachments entity
    :type byte_size: int
    :param content: The content property for the generalLedgerEntryAttachments
     entity
    :type content: str
    :param created_date_time: The createdDateTime property for the
     generalLedgerEntryAttachments entity
    :type created_date_time: datetime
    :param general_ledger_entry:
    :type general_ledger_entry:
     ~azure.mgmt.devtestlabs.models.GeneralLedgerEntry
    """

    _validation = {
        'file_name': {'max_length': 250},
    }

    _attribute_map = {
        'general_ledger_entry_number': {'key': 'generalLedgerEntryNumber', 'type': 'int'},
        'id': {'key': 'id', 'type': 'str'},
        'file_name': {'key': 'fileName', 'type': 'str'},
        'byte_size': {'key': 'byteSize', 'type': 'int'},
        'content': {'key': 'content', 'type': 'str'},
        'created_date_time': {'key': 'createdDateTime', 'type': 'iso-8601'},
        'general_ledger_entry': {'key': 'generalLedgerEntry', 'type': 'GeneralLedgerEntry'},
    }

    def __init__(self, *, general_ledger_entry_number: int=None, id: str=None, file_name: str=None, byte_size: int=None, content: str=None, created_date_time=None, general_ledger_entry=None, **kwargs) -> None:
        super(GeneralLedgerEntryAttachments, self).__init__(**kwargs)
        self.general_ledger_entry_number = general_ledger_entry_number
        self.id = id
        self.file_name = file_name
        self.byte_size = byte_size
        self.content = content
        self.created_date_time = created_date_time
        self.general_ledger_entry = general_ledger_entry
