# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class GeneralLedgerEntry(Model):
    """GeneralLedgerEntry.

    :param id: The id property for the generalLedgerEntry entity
    :type id: int
    :param posting_date: The postingDate property for the generalLedgerEntry
     entity
    :type posting_date: datetime
    :param document_number: The documentNumber property for the
     generalLedgerEntry entity
    :type document_number: str
    :param document_type: The documentType property for the generalLedgerEntry
     entity
    :type document_type: str
    :param account_id: The accountId property for the generalLedgerEntry
     entity
    :type account_id: str
    :param account_number: The accountNumber property for the
     generalLedgerEntry entity
    :type account_number: str
    :param description: The description property for the generalLedgerEntry
     entity
    :type description: str
    :param debit_amount: The debitAmount property for the generalLedgerEntry
     entity
    :type debit_amount: decimal.Decimal
    :param credit_amount: The creditAmount property for the generalLedgerEntry
     entity
    :type credit_amount: decimal.Decimal
    :param dimensions:
    :type dimensions: list[~azure.mgmt.devtestlabs.models.Dimensiontype]
    :param last_modified_date_time: The lastModifiedDateTime property for the
     generalLedgerEntry entity
    :type last_modified_date_time: datetime
    :param account:
    :type account: ~azure.mgmt.devtestlabs.models.Account
    """

    _validation = {
        'document_number': {'max_length': 20},
        'account_number': {'max_length': 20},
        'description': {'max_length': 100},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'int'},
        'posting_date': {'key': 'postingDate', 'type': 'iso-8601'},
        'document_number': {'key': 'documentNumber', 'type': 'str'},
        'document_type': {'key': 'documentType', 'type': 'str'},
        'account_id': {'key': 'accountId', 'type': 'str'},
        'account_number': {'key': 'accountNumber', 'type': 'str'},
        'description': {'key': 'description', 'type': 'str'},
        'debit_amount': {'key': 'debitAmount', 'type': 'decimal'},
        'credit_amount': {'key': 'creditAmount', 'type': 'decimal'},
        'dimensions': {'key': 'dimensions', 'type': '[Dimensiontype]'},
        'last_modified_date_time': {'key': 'lastModifiedDateTime', 'type': 'iso-8601'},
        'account': {'key': 'account', 'type': 'Account'},
    }

    def __init__(self, *, id: int=None, posting_date=None, document_number: str=None, document_type: str=None, account_id: str=None, account_number: str=None, description: str=None, debit_amount=None, credit_amount=None, dimensions=None, last_modified_date_time=None, account=None, **kwargs) -> None:
        super(GeneralLedgerEntry, self).__init__(**kwargs)
        self.id = id
        self.posting_date = posting_date
        self.document_number = document_number
        self.document_type = document_type
        self.account_id = account_id
        self.account_number = account_number
        self.description = description
        self.debit_amount = debit_amount
        self.credit_amount = credit_amount
        self.dimensions = dimensions
        self.last_modified_date_time = last_modified_date_time
        self.account = account
