# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class JournalLine(Model):
    """JournalLine.

    :param id: The id property for the journalLine entity
    :type id: str
    :param journal_display_name: The journalDisplayName property for the
     journalLine entity
    :type journal_display_name: str
    :param line_number: The lineNumber property for the journalLine entity
    :type line_number: int
    :param account_id: The accountId property for the journalLine entity
    :type account_id: str
    :param account_number: The accountNumber property for the journalLine
     entity
    :type account_number: str
    :param posting_date: The postingDate property for the journalLine entity
    :type posting_date: datetime
    :param document_number: The documentNumber property for the journalLine
     entity
    :type document_number: str
    :param external_document_number: The externalDocumentNumber property for
     the journalLine entity
    :type external_document_number: str
    :param amount: The amount property for the journalLine entity
    :type amount: decimal.Decimal
    :param description: The description property for the journalLine entity
    :type description: str
    :param comment: The comment property for the journalLine entity
    :type comment: str
    :param dimensions:
    :type dimensions: list[~azure.mgmt.devtestlabs.models.Dimensiontype]
    :param last_modified_date_time: The lastModifiedDateTime property for the
     journalLine entity
    :type last_modified_date_time: datetime
    :param attachments:
    :type attachments: list[~azure.mgmt.devtestlabs.models.Attachments]
    :param account:
    :type account: ~azure.mgmt.devtestlabs.models.Account
    """

    _validation = {
        'account_number': {'max_length': 20},
        'document_number': {'max_length': 20},
        'external_document_number': {'max_length': 35},
        'description': {'max_length': 100},
        'comment': {'max_length': 250},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'journal_display_name': {'key': 'journalDisplayName', 'type': 'str'},
        'line_number': {'key': 'lineNumber', 'type': 'int'},
        'account_id': {'key': 'accountId', 'type': 'str'},
        'account_number': {'key': 'accountNumber', 'type': 'str'},
        'posting_date': {'key': 'postingDate', 'type': 'iso-8601'},
        'document_number': {'key': 'documentNumber', 'type': 'str'},
        'external_document_number': {'key': 'externalDocumentNumber', 'type': 'str'},
        'amount': {'key': 'amount', 'type': 'decimal'},
        'description': {'key': 'description', 'type': 'str'},
        'comment': {'key': 'comment', 'type': 'str'},
        'dimensions': {'key': 'dimensions', 'type': '[Dimensiontype]'},
        'last_modified_date_time': {'key': 'lastModifiedDateTime', 'type': 'iso-8601'},
        'attachments': {'key': 'attachments', 'type': '[Attachments]'},
        'account': {'key': 'account', 'type': 'Account'},
    }

    def __init__(self, *, id: str=None, journal_display_name: str=None, line_number: int=None, account_id: str=None, account_number: str=None, posting_date=None, document_number: str=None, external_document_number: str=None, amount=None, description: str=None, comment: str=None, dimensions=None, last_modified_date_time=None, attachments=None, account=None, **kwargs) -> None:
        super(JournalLine, self).__init__(**kwargs)
        self.id = id
        self.journal_display_name = journal_display_name
        self.line_number = line_number
        self.account_id = account_id
        self.account_number = account_number
        self.posting_date = posting_date
        self.document_number = document_number
        self.external_document_number = external_document_number
        self.amount = amount
        self.description = description
        self.comment = comment
        self.dimensions = dimensions
        self.last_modified_date_time = last_modified_date_time
        self.attachments = attachments
        self.account = account
