# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class JournalLine(Model):
    """JournalLine.

    :param id: The id property for the journalLine entity
    :type id: str
    :param journal_display_name: The journalDisplayName property for the
     journalLine entity
    :type journal_display_name: str
    :param line_number: The lineNumber property for the journalLine entity
    :type line_number: int
    :param account_id: The accountId property for the journalLine entity
    :type account_id: str
    :param account_number: The accountNumber property for the journalLine
     entity
    :type account_number: str
    :param posting_date: The postingDate property for the journalLine entity
    :type posting_date: datetime
    :param document_number: The documentNumber property for the journalLine
     entity
    :type document_number: str
    :param external_document_number: The externalDocumentNumber property for
     the journalLine entity
    :type external_document_number: str
    :param amount: The amount property for the journalLine entity
    :type amount: decimal.Decimal
    :param description: The description property for the journalLine entity
    :type description: str
    :param comment: The comment property for the journalLine entity
    :type comment: str
    :param dimensions:
    :type dimensions: list[~azure.mgmt.devtestlabs.models.Dimensiontype]
    :param last_modified_date_time: The lastModifiedDateTime property for the
     journalLine entity
    :type last_modified_date_time: datetime
    :param attachments:
    :type attachments: list[~azure.mgmt.devtestlabs.models.Attachments]
    :param account:
    :type account: ~azure.mgmt.devtestlabs.models.Account
    """

    _validation = {
        'account_number': {'max_length': 20},
        'document_number': {'max_length': 20},
        'external_document_number': {'max_length': 35},
        'description': {'max_length': 100},
        'comment': {'max_length': 250},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'journal_display_name': {'key': 'journalDisplayName', 'type': 'str'},
        'line_number': {'key': 'lineNumber', 'type': 'int'},
        'account_id': {'key': 'accountId', 'type': 'str'},
        'account_number': {'key': 'accountNumber', 'type': 'str'},
        'posting_date': {'key': 'postingDate', 'type': 'iso-8601'},
        'document_number': {'key': 'documentNumber', 'type': 'str'},
        'external_document_number': {'key': 'externalDocumentNumber', 'type': 'str'},
        'amount': {'key': 'amount', 'type': 'decimal'},
        'description': {'key': 'description', 'type': 'str'},
        'comment': {'key': 'comment', 'type': 'str'},
        'dimensions': {'key': 'dimensions', 'type': '[Dimensiontype]'},
        'last_modified_date_time': {'key': 'lastModifiedDateTime', 'type': 'iso-8601'},
        'attachments': {'key': 'attachments', 'type': '[Attachments]'},
        'account': {'key': 'account', 'type': 'Account'},
    }

    def __init__(self, **kwargs):
        super(JournalLine, self).__init__(**kwargs)
        self.id = kwargs.get('id', None)
        self.journal_display_name = kwargs.get('journal_display_name', None)
        self.line_number = kwargs.get('line_number', None)
        self.account_id = kwargs.get('account_id', None)
        self.account_number = kwargs.get('account_number', None)
        self.posting_date = kwargs.get('posting_date', None)
        self.document_number = kwargs.get('document_number', None)
        self.external_document_number = kwargs.get('external_document_number', None)
        self.amount = kwargs.get('amount', None)
        self.description = kwargs.get('description', None)
        self.comment = kwargs.get('comment', None)
        self.dimensions = kwargs.get('dimensions', None)
        self.last_modified_date_time = kwargs.get('last_modified_date_time', None)
        self.attachments = kwargs.get('attachments', None)
        self.account = kwargs.get('account', None)
