# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class Journal(Model):
    """Journal.

    :param id: The id property for the journal entity
    :type id: str
    :param code: The code property for the journal entity
    :type code: str
    :param display_name: The displayName property for the journal entity
    :type display_name: str
    :param last_modified_date_time: The lastModifiedDateTime property for the
     journal entity
    :type last_modified_date_time: datetime
    :param balancing_account_id: The balancingAccountId property for the
     journal entity
    :type balancing_account_id: str
    :param balancing_account_number: The balancingAccountNumber property for
     the journal entity
    :type balancing_account_number: str
    :param journal_lines:
    :type journal_lines: list[~azure.mgmt.devtestlabs.models.JournalLine]
    :param account:
    :type account: ~azure.mgmt.devtestlabs.models.Account
    """

    _validation = {
        'code': {'max_length': 10},
        'display_name': {'max_length': 100},
        'balancing_account_number': {'max_length': 20},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'code': {'key': 'code', 'type': 'str'},
        'display_name': {'key': 'displayName', 'type': 'str'},
        'last_modified_date_time': {'key': 'lastModifiedDateTime', 'type': 'iso-8601'},
        'balancing_account_id': {'key': 'balancingAccountId', 'type': 'str'},
        'balancing_account_number': {'key': 'balancingAccountNumber', 'type': 'str'},
        'journal_lines': {'key': 'journalLines', 'type': '[JournalLine]'},
        'account': {'key': 'account', 'type': 'Account'},
    }

    def __init__(self, **kwargs):
        super(Journal, self).__init__(**kwargs)
        self.id = kwargs.get('id', None)
        self.code = kwargs.get('code', None)
        self.display_name = kwargs.get('display_name', None)
        self.last_modified_date_time = kwargs.get('last_modified_date_time', None)
        self.balancing_account_id = kwargs.get('balancing_account_id', None)
        self.balancing_account_number = kwargs.get('balancing_account_number', None)
        self.journal_lines = kwargs.get('journal_lines', None)
        self.account = kwargs.get('account', None)
