# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class PdfDocument(Model):
    """PdfDocument.

    :param id: The id property for the pdfDocument entity
    :type id: str
    :param content: The content property for the pdfDocument entity
    :type content: str
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'content': {'key': 'content', 'type': 'str'},
    }

    def __init__(self, *, id: str=None, content: str=None, **kwargs) -> None:
        super(PdfDocument, self).__init__(**kwargs)
        self.id = id
        self.content = content
