# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class Picture(Model):
    """Picture.

    :param id: The id property for the picture entity
    :type id: str
    :param width: The width property for the picture entity
    :type width: int
    :param height: The height property for the picture entity
    :type height: int
    :param content_type: The contentType property for the picture entity
    :type content_type: str
    :param content: The content property for the picture entity
    :type content: str
    """

    _validation = {
        'content_type': {'max_length': 100},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'width': {'key': 'width', 'type': 'int'},
        'height': {'key': 'height', 'type': 'int'},
        'content_type': {'key': 'contentType', 'type': 'str'},
        'content': {'key': 'content', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(Picture, self).__init__(**kwargs)
        self.id = kwargs.get('id', None)
        self.width = kwargs.get('width', None)
        self.height = kwargs.get('height', None)
        self.content_type = kwargs.get('content_type', None)
        self.content = kwargs.get('content', None)
