# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class Postaladdresstype(Model):
    """Postaladdresstype.

    :param street: The street property for the postaladdresstype entity
    :type street: str
    :param city: The city property for the postaladdresstype entity
    :type city: str
    :param state: The state property for the postaladdresstype entity
    :type state: str
    :param country_letter_code: The countryLetterCode property for the
     postaladdresstype entity
    :type country_letter_code: str
    :param postal_code: The postalCode property for the postaladdresstype
     entity
    :type postal_code: str
    :param customer_financial_details:
    :type customer_financial_details:
     list[~azure.mgmt.devtestlabs.models.CustomerFinancialDetail]
    :param picture:
    :type picture: list[~azure.mgmt.devtestlabs.models.Picture]
    :param default_dimensions:
    :type default_dimensions:
     list[~azure.mgmt.devtestlabs.models.DefaultDimensions]
    :param currency:
    :type currency: ~azure.mgmt.devtestlabs.models.Currency
    :param payment_term:
    :type payment_term: ~azure.mgmt.devtestlabs.models.PaymentTerm
    :param shipment_method:
    :type shipment_method: ~azure.mgmt.devtestlabs.models.ShipmentMethod
    :param payment_method:
    :type payment_method: ~azure.mgmt.devtestlabs.models.PaymentMethod
    """

    _validation = {
        'street': {'max_length': 152},
        'city': {'max_length': 30},
        'state': {'max_length': 30},
        'country_letter_code': {'max_length': 10},
        'postal_code': {'max_length': 20},
    }

    _attribute_map = {
        'street': {'key': 'street', 'type': 'str'},
        'city': {'key': 'city', 'type': 'str'},
        'state': {'key': 'state', 'type': 'str'},
        'country_letter_code': {'key': 'countryLetterCode', 'type': 'str'},
        'postal_code': {'key': 'postalCode', 'type': 'str'},
        'customer_financial_details': {'key': 'customerFinancialDetails', 'type': '[CustomerFinancialDetail]'},
        'picture': {'key': 'picture', 'type': '[Picture]'},
        'default_dimensions': {'key': 'defaultDimensions', 'type': '[DefaultDimensions]'},
        'currency': {'key': 'currency', 'type': 'Currency'},
        'payment_term': {'key': 'paymentTerm', 'type': 'PaymentTerm'},
        'shipment_method': {'key': 'shipmentMethod', 'type': 'ShipmentMethod'},
        'payment_method': {'key': 'paymentMethod', 'type': 'PaymentMethod'},
    }

    def __init__(self, *, street: str=None, city: str=None, state: str=None, country_letter_code: str=None, postal_code: str=None, customer_financial_details=None, picture=None, default_dimensions=None, currency=None, payment_term=None, shipment_method=None, payment_method=None, **kwargs) -> None:
        super(Postaladdresstype, self).__init__(**kwargs)
        self.street = street
        self.city = city
        self.state = state
        self.country_letter_code = country_letter_code
        self.postal_code = postal_code
        self.customer_financial_details = customer_financial_details
        self.picture = picture
        self.default_dimensions = default_dimensions
        self.currency = currency
        self.payment_term = payment_term
        self.shipment_method = shipment_method
        self.payment_method = payment_method
