# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class PurchaseInvoice(Model):
    """PurchaseInvoice.

    :param id: The id property for the purchaseInvoice entity
    :type id: str
    :param number: The number property for the purchaseInvoice entity
    :type number: str
    :param invoice_date: The invoiceDate property for the purchaseInvoice
     entity
    :type invoice_date: datetime
    :param due_date: The dueDate property for the purchaseInvoice entity
    :type due_date: datetime
    :param vendor_invoice_number: The vendorInvoiceNumber property for the
     purchaseInvoice entity
    :type vendor_invoice_number: str
    :param vendor_id: The vendorId property for the purchaseInvoice entity
    :type vendor_id: str
    :param vendor_number: The vendorNumber property for the purchaseInvoice
     entity
    :type vendor_number: str
    :param vendor_name: The vendorName property for the purchaseInvoice entity
    :type vendor_name: str
    :param pay_to_name: The payToName property for the purchaseInvoice entity
    :type pay_to_name: str
    :param pay_to_contact: The payToContact property for the purchaseInvoice
     entity
    :type pay_to_contact: str
    :param pay_to_vendor_id: The payToVendorId property for the
     purchaseInvoice entity
    :type pay_to_vendor_id: str
    :param pay_to_vendor_number: The payToVendorNumber property for the
     purchaseInvoice entity
    :type pay_to_vendor_number: str
    :param ship_to_name: The shipToName property for the purchaseInvoice
     entity
    :type ship_to_name: str
    :param ship_to_contact: The shipToContact property for the purchaseInvoice
     entity
    :type ship_to_contact: str
    :param buy_from_address:
    :type buy_from_address: ~azure.mgmt.devtestlabs.models.Postaladdresstype
    :param pay_to_address:
    :type pay_to_address: ~azure.mgmt.devtestlabs.models.Postaladdresstype
    :param ship_to_address:
    :type ship_to_address: ~azure.mgmt.devtestlabs.models.Postaladdresstype
    :param currency_id: The currencyId property for the purchaseInvoice entity
    :type currency_id: str
    :param currency_code: The currencyCode property for the purchaseInvoice
     entity
    :type currency_code: str
    :param prices_include_tax: The pricesIncludeTax property for the
     purchaseInvoice entity
    :type prices_include_tax: bool
    :param discount_amount: The discountAmount property for the
     purchaseInvoice entity
    :type discount_amount: decimal.Decimal
    :param discount_applied_before_tax: The discountAppliedBeforeTax property
     for the purchaseInvoice entity
    :type discount_applied_before_tax: bool
    :param total_amount_excluding_tax: The totalAmountExcludingTax property
     for the purchaseInvoice entity
    :type total_amount_excluding_tax: decimal.Decimal
    :param total_tax_amount: The totalTaxAmount property for the
     purchaseInvoice entity
    :type total_tax_amount: decimal.Decimal
    :param total_amount_including_tax: The totalAmountIncludingTax property
     for the purchaseInvoice entity
    :type total_amount_including_tax: decimal.Decimal
    :param status: The status property for the purchaseInvoice entity
    :type status: str
    :param last_modified_date_time: The lastModifiedDateTime property for the
     purchaseInvoice entity
    :type last_modified_date_time: datetime
    :param purchase_invoice_lines:
    :type purchase_invoice_lines:
     list[~azure.mgmt.devtestlabs.models.PurchaseInvoiceLine]
    :param pdf_document:
    :type pdf_document: list[~azure.mgmt.devtestlabs.models.PdfDocument]
    :param vendor:
    :type vendor: ~azure.mgmt.devtestlabs.models.Vendor
    :param currency:
    :type currency: ~azure.mgmt.devtestlabs.models.Currency
    """

    _validation = {
        'number': {'max_length': 20},
        'vendor_invoice_number': {'max_length': 35},
        'vendor_number': {'max_length': 20},
        'vendor_name': {'max_length': 100},
        'pay_to_name': {'max_length': 100},
        'pay_to_contact': {'max_length': 100},
        'pay_to_vendor_number': {'max_length': 20},
        'ship_to_name': {'max_length': 100},
        'ship_to_contact': {'max_length': 100},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'number': {'key': 'number', 'type': 'str'},
        'invoice_date': {'key': 'invoiceDate', 'type': 'iso-8601'},
        'due_date': {'key': 'dueDate', 'type': 'iso-8601'},
        'vendor_invoice_number': {'key': 'vendorInvoiceNumber', 'type': 'str'},
        'vendor_id': {'key': 'vendorId', 'type': 'str'},
        'vendor_number': {'key': 'vendorNumber', 'type': 'str'},
        'vendor_name': {'key': 'vendorName', 'type': 'str'},
        'pay_to_name': {'key': 'payToName', 'type': 'str'},
        'pay_to_contact': {'key': 'payToContact', 'type': 'str'},
        'pay_to_vendor_id': {'key': 'payToVendorId', 'type': 'str'},
        'pay_to_vendor_number': {'key': 'payToVendorNumber', 'type': 'str'},
        'ship_to_name': {'key': 'shipToName', 'type': 'str'},
        'ship_to_contact': {'key': 'shipToContact', 'type': 'str'},
        'buy_from_address': {'key': 'buyFromAddress', 'type': 'Postaladdresstype'},
        'pay_to_address': {'key': 'payToAddress', 'type': 'Postaladdresstype'},
        'ship_to_address': {'key': 'shipToAddress', 'type': 'Postaladdresstype'},
        'currency_id': {'key': 'currencyId', 'type': 'str'},
        'currency_code': {'key': 'currencyCode', 'type': 'str'},
        'prices_include_tax': {'key': 'pricesIncludeTax', 'type': 'bool'},
        'discount_amount': {'key': 'discountAmount', 'type': 'decimal'},
        'discount_applied_before_tax': {'key': 'discountAppliedBeforeTax', 'type': 'bool'},
        'total_amount_excluding_tax': {'key': 'totalAmountExcludingTax', 'type': 'decimal'},
        'total_tax_amount': {'key': 'totalTaxAmount', 'type': 'decimal'},
        'total_amount_including_tax': {'key': 'totalAmountIncludingTax', 'type': 'decimal'},
        'status': {'key': 'status', 'type': 'str'},
        'last_modified_date_time': {'key': 'lastModifiedDateTime', 'type': 'iso-8601'},
        'purchase_invoice_lines': {'key': 'purchaseInvoiceLines', 'type': '[PurchaseInvoiceLine]'},
        'pdf_document': {'key': 'pdfDocument', 'type': '[PdfDocument]'},
        'vendor': {'key': 'vendor', 'type': 'Vendor'},
        'currency': {'key': 'currency', 'type': 'Currency'},
    }

    def __init__(self, *, id: str=None, number: str=None, invoice_date=None, due_date=None, vendor_invoice_number: str=None, vendor_id: str=None, vendor_number: str=None, vendor_name: str=None, pay_to_name: str=None, pay_to_contact: str=None, pay_to_vendor_id: str=None, pay_to_vendor_number: str=None, ship_to_name: str=None, ship_to_contact: str=None, buy_from_address=None, pay_to_address=None, ship_to_address=None, currency_id: str=None, currency_code: str=None, prices_include_tax: bool=None, discount_amount=None, discount_applied_before_tax: bool=None, total_amount_excluding_tax=None, total_tax_amount=None, total_amount_including_tax=None, status: str=None, last_modified_date_time=None, purchase_invoice_lines=None, pdf_document=None, vendor=None, currency=None, **kwargs) -> None:
        super(PurchaseInvoice, self).__init__(**kwargs)
        self.id = id
        self.number = number
        self.invoice_date = invoice_date
        self.due_date = due_date
        self.vendor_invoice_number = vendor_invoice_number
        self.vendor_id = vendor_id
        self.vendor_number = vendor_number
        self.vendor_name = vendor_name
        self.pay_to_name = pay_to_name
        self.pay_to_contact = pay_to_contact
        self.pay_to_vendor_id = pay_to_vendor_id
        self.pay_to_vendor_number = pay_to_vendor_number
        self.ship_to_name = ship_to_name
        self.ship_to_contact = ship_to_contact
        self.buy_from_address = buy_from_address
        self.pay_to_address = pay_to_address
        self.ship_to_address = ship_to_address
        self.currency_id = currency_id
        self.currency_code = currency_code
        self.prices_include_tax = prices_include_tax
        self.discount_amount = discount_amount
        self.discount_applied_before_tax = discount_applied_before_tax
        self.total_amount_excluding_tax = total_amount_excluding_tax
        self.total_tax_amount = total_tax_amount
        self.total_amount_including_tax = total_amount_including_tax
        self.status = status
        self.last_modified_date_time = last_modified_date_time
        self.purchase_invoice_lines = purchase_invoice_lines
        self.pdf_document = pdf_document
        self.vendor = vendor
        self.currency = currency
