# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class RetainedEarningsStatement(Model):
    """RetainedEarningsStatement.

    :param line_number: The lineNumber property for the
     retainedEarningsStatement entity
    :type line_number: int
    :param display: The display property for the retainedEarningsStatement
     entity
    :type display: str
    :param net_change: The netChange property for the
     retainedEarningsStatement entity
    :type net_change: decimal.Decimal
    :param line_type: The lineType property for the retainedEarningsStatement
     entity
    :type line_type: str
    :param indentation: The indentation property for the
     retainedEarningsStatement entity
    :type indentation: int
    :param date_filter: The dateFilter property for the
     retainedEarningsStatement entity
    :type date_filter: datetime
    """

    _validation = {
        'display': {'max_length': 250},
        'line_type': {'max_length': 30},
    }

    _attribute_map = {
        'line_number': {'key': 'lineNumber', 'type': 'int'},
        'display': {'key': 'display', 'type': 'str'},
        'net_change': {'key': 'netChange', 'type': 'decimal'},
        'line_type': {'key': 'lineType', 'type': 'str'},
        'indentation': {'key': 'indentation', 'type': 'int'},
        'date_filter': {'key': 'dateFilter', 'type': 'iso-8601'},
    }

    def __init__(self, **kwargs):
        super(RetainedEarningsStatement, self).__init__(**kwargs)
        self.line_number = kwargs.get('line_number', None)
        self.display = kwargs.get('display', None)
        self.net_change = kwargs.get('net_change', None)
        self.line_type = kwargs.get('line_type', None)
        self.indentation = kwargs.get('indentation', None)
        self.date_filter = kwargs.get('date_filter', None)
