# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class SalesCreditMemo(Model):
    """SalesCreditMemo.

    :param id: The id property for the salesCreditMemo entity
    :type id: str
    :param number: The number property for the salesCreditMemo entity
    :type number: str
    :param external_document_number: The externalDocumentNumber property for
     the salesCreditMemo entity
    :type external_document_number: str
    :param credit_memo_date: The creditMemoDate property for the
     salesCreditMemo entity
    :type credit_memo_date: datetime
    :param due_date: The dueDate property for the salesCreditMemo entity
    :type due_date: datetime
    :param customer_id: The customerId property for the salesCreditMemo entity
    :type customer_id: str
    :param contact_id: The contactId property for the salesCreditMemo entity
    :type contact_id: str
    :param customer_number: The customerNumber property for the
     salesCreditMemo entity
    :type customer_number: str
    :param customer_name: The customerName property for the salesCreditMemo
     entity
    :type customer_name: str
    :param bill_to_name: The billToName property for the salesCreditMemo
     entity
    :type bill_to_name: str
    :param bill_to_customer_id: The billToCustomerId property for the
     salesCreditMemo entity
    :type bill_to_customer_id: str
    :param bill_to_customer_number: The billToCustomerNumber property for the
     salesCreditMemo entity
    :type bill_to_customer_number: str
    :param selling_postal_address:
    :type selling_postal_address:
     ~azure.mgmt.devtestlabs.models.Postaladdresstype
    :param billing_postal_address:
    :type billing_postal_address:
     ~azure.mgmt.devtestlabs.models.Postaladdresstype
    :param currency_id: The currencyId property for the salesCreditMemo entity
    :type currency_id: str
    :param currency_code: The currencyCode property for the salesCreditMemo
     entity
    :type currency_code: str
    :param payment_terms_id: The paymentTermsId property for the
     salesCreditMemo entity
    :type payment_terms_id: str
    :param salesperson: The salesperson property for the salesCreditMemo
     entity
    :type salesperson: str
    :param prices_include_tax: The pricesIncludeTax property for the
     salesCreditMemo entity
    :type prices_include_tax: bool
    :param discount_amount: The discountAmount property for the
     salesCreditMemo entity
    :type discount_amount: decimal.Decimal
    :param discount_applied_before_tax: The discountAppliedBeforeTax property
     for the salesCreditMemo entity
    :type discount_applied_before_tax: bool
    :param total_amount_excluding_tax: The totalAmountExcludingTax property
     for the salesCreditMemo entity
    :type total_amount_excluding_tax: decimal.Decimal
    :param total_tax_amount: The totalTaxAmount property for the
     salesCreditMemo entity
    :type total_tax_amount: decimal.Decimal
    :param total_amount_including_tax: The totalAmountIncludingTax property
     for the salesCreditMemo entity
    :type total_amount_including_tax: decimal.Decimal
    :param status: The status property for the salesCreditMemo entity
    :type status: str
    :param last_modified_date_time: The lastModifiedDateTime property for the
     salesCreditMemo entity
    :type last_modified_date_time: datetime
    :param invoice_id: The invoiceId property for the salesCreditMemo entity
    :type invoice_id: str
    :param invoice_number: The invoiceNumber property for the salesCreditMemo
     entity
    :type invoice_number: str
    :param phone_number: The phoneNumber property for the salesCreditMemo
     entity
    :type phone_number: str
    :param email: The email property for the salesCreditMemo entity
    :type email: str
    :param sales_credit_memo_lines:
    :type sales_credit_memo_lines:
     list[~azure.mgmt.devtestlabs.models.SalesCreditMemoLine]
    :param pdf_document:
    :type pdf_document: list[~azure.mgmt.devtestlabs.models.PdfDocument]
    :param customer:
    :type customer: ~azure.mgmt.devtestlabs.models.Customer
    :param currency:
    :type currency: ~azure.mgmt.devtestlabs.models.Currency
    :param payment_term:
    :type payment_term: ~azure.mgmt.devtestlabs.models.PaymentTerm
    """

    _validation = {
        'number': {'max_length': 20},
        'external_document_number': {'max_length': 35},
        'contact_id': {'max_length': 250},
        'customer_number': {'max_length': 20},
        'customer_name': {'max_length': 100},
        'bill_to_name': {'max_length': 100},
        'bill_to_customer_number': {'max_length': 20},
        'salesperson': {'max_length': 20},
        'invoice_number': {'max_length': 20},
        'phone_number': {'max_length': 30},
        'email': {'max_length': 80},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'number': {'key': 'number', 'type': 'str'},
        'external_document_number': {'key': 'externalDocumentNumber', 'type': 'str'},
        'credit_memo_date': {'key': 'creditMemoDate', 'type': 'iso-8601'},
        'due_date': {'key': 'dueDate', 'type': 'iso-8601'},
        'customer_id': {'key': 'customerId', 'type': 'str'},
        'contact_id': {'key': 'contactId', 'type': 'str'},
        'customer_number': {'key': 'customerNumber', 'type': 'str'},
        'customer_name': {'key': 'customerName', 'type': 'str'},
        'bill_to_name': {'key': 'billToName', 'type': 'str'},
        'bill_to_customer_id': {'key': 'billToCustomerId', 'type': 'str'},
        'bill_to_customer_number': {'key': 'billToCustomerNumber', 'type': 'str'},
        'selling_postal_address': {'key': 'sellingPostalAddress', 'type': 'Postaladdresstype'},
        'billing_postal_address': {'key': 'billingPostalAddress', 'type': 'Postaladdresstype'},
        'currency_id': {'key': 'currencyId', 'type': 'str'},
        'currency_code': {'key': 'currencyCode', 'type': 'str'},
        'payment_terms_id': {'key': 'paymentTermsId', 'type': 'str'},
        'salesperson': {'key': 'salesperson', 'type': 'str'},
        'prices_include_tax': {'key': 'pricesIncludeTax', 'type': 'bool'},
        'discount_amount': {'key': 'discountAmount', 'type': 'decimal'},
        'discount_applied_before_tax': {'key': 'discountAppliedBeforeTax', 'type': 'bool'},
        'total_amount_excluding_tax': {'key': 'totalAmountExcludingTax', 'type': 'decimal'},
        'total_tax_amount': {'key': 'totalTaxAmount', 'type': 'decimal'},
        'total_amount_including_tax': {'key': 'totalAmountIncludingTax', 'type': 'decimal'},
        'status': {'key': 'status', 'type': 'str'},
        'last_modified_date_time': {'key': 'lastModifiedDateTime', 'type': 'iso-8601'},
        'invoice_id': {'key': 'invoiceId', 'type': 'str'},
        'invoice_number': {'key': 'invoiceNumber', 'type': 'str'},
        'phone_number': {'key': 'phoneNumber', 'type': 'str'},
        'email': {'key': 'email', 'type': 'str'},
        'sales_credit_memo_lines': {'key': 'salesCreditMemoLines', 'type': '[SalesCreditMemoLine]'},
        'pdf_document': {'key': 'pdfDocument', 'type': '[PdfDocument]'},
        'customer': {'key': 'customer', 'type': 'Customer'},
        'currency': {'key': 'currency', 'type': 'Currency'},
        'payment_term': {'key': 'paymentTerm', 'type': 'PaymentTerm'},
    }

    def __init__(self, *, id: str=None, number: str=None, external_document_number: str=None, credit_memo_date=None, due_date=None, customer_id: str=None, contact_id: str=None, customer_number: str=None, customer_name: str=None, bill_to_name: str=None, bill_to_customer_id: str=None, bill_to_customer_number: str=None, selling_postal_address=None, billing_postal_address=None, currency_id: str=None, currency_code: str=None, payment_terms_id: str=None, salesperson: str=None, prices_include_tax: bool=None, discount_amount=None, discount_applied_before_tax: bool=None, total_amount_excluding_tax=None, total_tax_amount=None, total_amount_including_tax=None, status: str=None, last_modified_date_time=None, invoice_id: str=None, invoice_number: str=None, phone_number: str=None, email: str=None, sales_credit_memo_lines=None, pdf_document=None, customer=None, currency=None, payment_term=None, **kwargs) -> None:
        super(SalesCreditMemo, self).__init__(**kwargs)
        self.id = id
        self.number = number
        self.external_document_number = external_document_number
        self.credit_memo_date = credit_memo_date
        self.due_date = due_date
        self.customer_id = customer_id
        self.contact_id = contact_id
        self.customer_number = customer_number
        self.customer_name = customer_name
        self.bill_to_name = bill_to_name
        self.bill_to_customer_id = bill_to_customer_id
        self.bill_to_customer_number = bill_to_customer_number
        self.selling_postal_address = selling_postal_address
        self.billing_postal_address = billing_postal_address
        self.currency_id = currency_id
        self.currency_code = currency_code
        self.payment_terms_id = payment_terms_id
        self.salesperson = salesperson
        self.prices_include_tax = prices_include_tax
        self.discount_amount = discount_amount
        self.discount_applied_before_tax = discount_applied_before_tax
        self.total_amount_excluding_tax = total_amount_excluding_tax
        self.total_tax_amount = total_tax_amount
        self.total_amount_including_tax = total_amount_including_tax
        self.status = status
        self.last_modified_date_time = last_modified_date_time
        self.invoice_id = invoice_id
        self.invoice_number = invoice_number
        self.phone_number = phone_number
        self.email = email
        self.sales_credit_memo_lines = sales_credit_memo_lines
        self.pdf_document = pdf_document
        self.customer = customer
        self.currency = currency
        self.payment_term = payment_term
