# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class SalesQuote(Model):
    """SalesQuote.

    :param id: The id property for the salesQuote entity
    :type id: str
    :param number: The number property for the salesQuote entity
    :type number: str
    :param external_document_number: The externalDocumentNumber property for
     the salesQuote entity
    :type external_document_number: str
    :param document_date: The documentDate property for the salesQuote entity
    :type document_date: datetime
    :param due_date: The dueDate property for the salesQuote entity
    :type due_date: datetime
    :param customer_id: The customerId property for the salesQuote entity
    :type customer_id: str
    :param contact_id: The contactId property for the salesQuote entity
    :type contact_id: str
    :param customer_number: The customerNumber property for the salesQuote
     entity
    :type customer_number: str
    :param customer_name: The customerName property for the salesQuote entity
    :type customer_name: str
    :param bill_to_name: The billToName property for the salesQuote entity
    :type bill_to_name: str
    :param bill_to_customer_id: The billToCustomerId property for the
     salesQuote entity
    :type bill_to_customer_id: str
    :param bill_to_customer_number: The billToCustomerNumber property for the
     salesQuote entity
    :type bill_to_customer_number: str
    :param ship_to_name: The shipToName property for the salesQuote entity
    :type ship_to_name: str
    :param ship_to_contact: The shipToContact property for the salesQuote
     entity
    :type ship_to_contact: str
    :param selling_postal_address:
    :type selling_postal_address:
     ~azure.mgmt.devtestlabs.models.Postaladdresstype
    :param billing_postal_address:
    :type billing_postal_address:
     ~azure.mgmt.devtestlabs.models.Postaladdresstype
    :param shipping_postal_address:
    :type shipping_postal_address:
     ~azure.mgmt.devtestlabs.models.Postaladdresstype
    :param currency_id: The currencyId property for the salesQuote entity
    :type currency_id: str
    :param currency_code: The currencyCode property for the salesQuote entity
    :type currency_code: str
    :param payment_terms_id: The paymentTermsId property for the salesQuote
     entity
    :type payment_terms_id: str
    :param shipment_method_id: The shipmentMethodId property for the
     salesQuote entity
    :type shipment_method_id: str
    :param salesperson: The salesperson property for the salesQuote entity
    :type salesperson: str
    :param discount_amount: The discountAmount property for the salesQuote
     entity
    :type discount_amount: decimal.Decimal
    :param total_amount_excluding_tax: The totalAmountExcludingTax property
     for the salesQuote entity
    :type total_amount_excluding_tax: decimal.Decimal
    :param total_tax_amount: The totalTaxAmount property for the salesQuote
     entity
    :type total_tax_amount: decimal.Decimal
    :param total_amount_including_tax: The totalAmountIncludingTax property
     for the salesQuote entity
    :type total_amount_including_tax: decimal.Decimal
    :param status: The status property for the salesQuote entity
    :type status: str
    :param sent_date: The sentDate property for the salesQuote entity
    :type sent_date: datetime
    :param valid_until_date: The validUntilDate property for the salesQuote
     entity
    :type valid_until_date: datetime
    :param accepted_date: The acceptedDate property for the salesQuote entity
    :type accepted_date: datetime
    :param last_modified_date_time: The lastModifiedDateTime property for the
     salesQuote entity
    :type last_modified_date_time: datetime
    :param phone_number: The phoneNumber property for the salesQuote entity
    :type phone_number: str
    :param email: The email property for the salesQuote entity
    :type email: str
    :param sales_quote_lines:
    :type sales_quote_lines:
     list[~azure.mgmt.devtestlabs.models.SalesQuoteLine]
    :param pdf_document:
    :type pdf_document: list[~azure.mgmt.devtestlabs.models.PdfDocument]
    :param customer:
    :type customer: ~azure.mgmt.devtestlabs.models.Customer
    :param currency:
    :type currency: ~azure.mgmt.devtestlabs.models.Currency
    :param payment_term:
    :type payment_term: ~azure.mgmt.devtestlabs.models.PaymentTerm
    :param shipment_method:
    :type shipment_method: ~azure.mgmt.devtestlabs.models.ShipmentMethod
    """

    _validation = {
        'number': {'max_length': 20},
        'external_document_number': {'max_length': 35},
        'contact_id': {'max_length': 250},
        'customer_number': {'max_length': 20},
        'customer_name': {'max_length': 100},
        'bill_to_name': {'max_length': 100},
        'bill_to_customer_number': {'max_length': 20},
        'ship_to_name': {'max_length': 100},
        'ship_to_contact': {'max_length': 100},
        'salesperson': {'max_length': 20},
        'phone_number': {'max_length': 30},
        'email': {'max_length': 80},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'number': {'key': 'number', 'type': 'str'},
        'external_document_number': {'key': 'externalDocumentNumber', 'type': 'str'},
        'document_date': {'key': 'documentDate', 'type': 'iso-8601'},
        'due_date': {'key': 'dueDate', 'type': 'iso-8601'},
        'customer_id': {'key': 'customerId', 'type': 'str'},
        'contact_id': {'key': 'contactId', 'type': 'str'},
        'customer_number': {'key': 'customerNumber', 'type': 'str'},
        'customer_name': {'key': 'customerName', 'type': 'str'},
        'bill_to_name': {'key': 'billToName', 'type': 'str'},
        'bill_to_customer_id': {'key': 'billToCustomerId', 'type': 'str'},
        'bill_to_customer_number': {'key': 'billToCustomerNumber', 'type': 'str'},
        'ship_to_name': {'key': 'shipToName', 'type': 'str'},
        'ship_to_contact': {'key': 'shipToContact', 'type': 'str'},
        'selling_postal_address': {'key': 'sellingPostalAddress', 'type': 'Postaladdresstype'},
        'billing_postal_address': {'key': 'billingPostalAddress', 'type': 'Postaladdresstype'},
        'shipping_postal_address': {'key': 'shippingPostalAddress', 'type': 'Postaladdresstype'},
        'currency_id': {'key': 'currencyId', 'type': 'str'},
        'currency_code': {'key': 'currencyCode', 'type': 'str'},
        'payment_terms_id': {'key': 'paymentTermsId', 'type': 'str'},
        'shipment_method_id': {'key': 'shipmentMethodId', 'type': 'str'},
        'salesperson': {'key': 'salesperson', 'type': 'str'},
        'discount_amount': {'key': 'discountAmount', 'type': 'decimal'},
        'total_amount_excluding_tax': {'key': 'totalAmountExcludingTax', 'type': 'decimal'},
        'total_tax_amount': {'key': 'totalTaxAmount', 'type': 'decimal'},
        'total_amount_including_tax': {'key': 'totalAmountIncludingTax', 'type': 'decimal'},
        'status': {'key': 'status', 'type': 'str'},
        'sent_date': {'key': 'sentDate', 'type': 'iso-8601'},
        'valid_until_date': {'key': 'validUntilDate', 'type': 'iso-8601'},
        'accepted_date': {'key': 'acceptedDate', 'type': 'iso-8601'},
        'last_modified_date_time': {'key': 'lastModifiedDateTime', 'type': 'iso-8601'},
        'phone_number': {'key': 'phoneNumber', 'type': 'str'},
        'email': {'key': 'email', 'type': 'str'},
        'sales_quote_lines': {'key': 'salesQuoteLines', 'type': '[SalesQuoteLine]'},
        'pdf_document': {'key': 'pdfDocument', 'type': '[PdfDocument]'},
        'customer': {'key': 'customer', 'type': 'Customer'},
        'currency': {'key': 'currency', 'type': 'Currency'},
        'payment_term': {'key': 'paymentTerm', 'type': 'PaymentTerm'},
        'shipment_method': {'key': 'shipmentMethod', 'type': 'ShipmentMethod'},
    }

    def __init__(self, *, id: str=None, number: str=None, external_document_number: str=None, document_date=None, due_date=None, customer_id: str=None, contact_id: str=None, customer_number: str=None, customer_name: str=None, bill_to_name: str=None, bill_to_customer_id: str=None, bill_to_customer_number: str=None, ship_to_name: str=None, ship_to_contact: str=None, selling_postal_address=None, billing_postal_address=None, shipping_postal_address=None, currency_id: str=None, currency_code: str=None, payment_terms_id: str=None, shipment_method_id: str=None, salesperson: str=None, discount_amount=None, total_amount_excluding_tax=None, total_tax_amount=None, total_amount_including_tax=None, status: str=None, sent_date=None, valid_until_date=None, accepted_date=None, last_modified_date_time=None, phone_number: str=None, email: str=None, sales_quote_lines=None, pdf_document=None, customer=None, currency=None, payment_term=None, shipment_method=None, **kwargs) -> None:
        super(SalesQuote, self).__init__(**kwargs)
        self.id = id
        self.number = number
        self.external_document_number = external_document_number
        self.document_date = document_date
        self.due_date = due_date
        self.customer_id = customer_id
        self.contact_id = contact_id
        self.customer_number = customer_number
        self.customer_name = customer_name
        self.bill_to_name = bill_to_name
        self.bill_to_customer_id = bill_to_customer_id
        self.bill_to_customer_number = bill_to_customer_number
        self.ship_to_name = ship_to_name
        self.ship_to_contact = ship_to_contact
        self.selling_postal_address = selling_postal_address
        self.billing_postal_address = billing_postal_address
        self.shipping_postal_address = shipping_postal_address
        self.currency_id = currency_id
        self.currency_code = currency_code
        self.payment_terms_id = payment_terms_id
        self.shipment_method_id = shipment_method_id
        self.salesperson = salesperson
        self.discount_amount = discount_amount
        self.total_amount_excluding_tax = total_amount_excluding_tax
        self.total_tax_amount = total_tax_amount
        self.total_amount_including_tax = total_amount_including_tax
        self.status = status
        self.sent_date = sent_date
        self.valid_until_date = valid_until_date
        self.accepted_date = accepted_date
        self.last_modified_date_time = last_modified_date_time
        self.phone_number = phone_number
        self.email = email
        self.sales_quote_lines = sales_quote_lines
        self.pdf_document = pdf_document
        self.customer = customer
        self.currency = currency
        self.payment_term = payment_term
        self.shipment_method = shipment_method
