# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class TaxGroup(Model):
    """TaxGroup.

    :param id: The id property for the taxGroup entity
    :type id: str
    :param code: The code property for the taxGroup entity
    :type code: str
    :param display_name: The displayName property for the taxGroup entity
    :type display_name: str
    :param tax_type: The taxType property for the taxGroup entity
    :type tax_type: str
    :param last_modified_date_time: The lastModifiedDateTime property for the
     taxGroup entity
    :type last_modified_date_time: datetime
    """

    _validation = {
        'code': {'max_length': 20},
        'display_name': {'max_length': 100},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'code': {'key': 'code', 'type': 'str'},
        'display_name': {'key': 'displayName', 'type': 'str'},
        'tax_type': {'key': 'taxType', 'type': 'str'},
        'last_modified_date_time': {'key': 'lastModifiedDateTime', 'type': 'iso-8601'},
    }

    def __init__(self, **kwargs):
        super(TaxGroup, self).__init__(**kwargs)
        self.id = kwargs.get('id', None)
        self.code = kwargs.get('code', None)
        self.display_name = kwargs.get('display_name', None)
        self.tax_type = kwargs.get('tax_type', None)
        self.last_modified_date_time = kwargs.get('last_modified_date_time', None)
