# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class TrialBalance(Model):
    """TrialBalance.

    :param number: The number property for the trialBalance entity
    :type number: str
    :param account_id: The accountId property for the trialBalance entity
    :type account_id: str
    :param account_type: The accountType property for the trialBalance entity
    :type account_type: str
    :param display: The display property for the trialBalance entity
    :type display: str
    :param total_debit: The totalDebit property for the trialBalance entity
    :type total_debit: str
    :param total_credit: The totalCredit property for the trialBalance entity
    :type total_credit: str
    :param balance_at_date_debit: The balanceAtDateDebit property for the
     trialBalance entity
    :type balance_at_date_debit: str
    :param balance_at_date_credit: The balanceAtDateCredit property for the
     trialBalance entity
    :type balance_at_date_credit: str
    :param date_filter: The dateFilter property for the trialBalance entity
    :type date_filter: datetime
    :param account:
    :type account: ~azure.mgmt.devtestlabs.models.Account
    """

    _validation = {
        'number': {'max_length': 20},
        'display': {'max_length': 100},
        'total_debit': {'max_length': 30},
        'total_credit': {'max_length': 30},
        'balance_at_date_debit': {'max_length': 30},
        'balance_at_date_credit': {'max_length': 30},
    }

    _attribute_map = {
        'number': {'key': 'number', 'type': 'str'},
        'account_id': {'key': 'accountId', 'type': 'str'},
        'account_type': {'key': 'accountType', 'type': 'str'},
        'display': {'key': 'display', 'type': 'str'},
        'total_debit': {'key': 'totalDebit', 'type': 'str'},
        'total_credit': {'key': 'totalCredit', 'type': 'str'},
        'balance_at_date_debit': {'key': 'balanceAtDateDebit', 'type': 'str'},
        'balance_at_date_credit': {'key': 'balanceAtDateCredit', 'type': 'str'},
        'date_filter': {'key': 'dateFilter', 'type': 'iso-8601'},
        'account': {'key': 'account', 'type': 'Account'},
    }

    def __init__(self, *, number: str=None, account_id: str=None, account_type: str=None, display: str=None, total_debit: str=None, total_credit: str=None, balance_at_date_debit: str=None, balance_at_date_credit: str=None, date_filter=None, account=None, **kwargs) -> None:
        super(TrialBalance, self).__init__(**kwargs)
        self.number = number
        self.account_id = account_id
        self.account_type = account_type
        self.display = display
        self.total_debit = total_debit
        self.total_credit = total_credit
        self.balance_at_date_debit = balance_at_date_debit
        self.balance_at_date_credit = balance_at_date_credit
        self.date_filter = date_filter
        self.account = account
