# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from typing import cast, TYPE_CHECKING
import logging
from ._models import CloudEvent, EventGridEvent

if TYPE_CHECKING:
    # pylint: disable=unused-import,ungrouped-imports
    from typing import Any, Union, Iterable

_LOGGER = logging.getLogger(__name__)

class EventGridDeserializer(object):
    """
    A consumer responsible for deserializing event handler messages, to allow for
    access to strongly typed Event objects.
    """
    def deserialize_cloud_events(self, cloud_event, **kwargs): # pylint: disable=no-self-use
        # type: (Union[str, dict, bytes], Any) -> Iterable[CloudEvent]
        """Single event following CloudEvent schema will be parsed and returned as Deserialized Event.
        :param cloud_event: The event to be deserialized.
        :type cloud_event: Union[str, dict, bytes]
        :rtype: Iterable[CloudEvent]

        :raise: :class:`ValueError`, when events do not follow CloudEvent schema.
        """
        encode = kwargs.pop('encoding', 'utf-8')
        try:
            cloud_event = CloudEvent._from_json(cloud_event, encode) # pylint: disable=protected-access
            event_list = []
            for event in cloud_event:
                deserialized_event = CloudEvent._from_generated(event) # pylint: disable=protected-access
                deserialized_event._deserialize_data(deserialized_event, deserialized_event.type) # pylint: disable=protected-access
                event_list.append(deserialized_event)
            return event_list
        except Exception as err:
            _LOGGER.error('Your event: %s', cloud_event)
            _LOGGER.error(err)
            raise ValueError('Error: cannot deserialize event. Event does not have a valid format. \
                Event must be a string, dict, or bytes following the CloudEvent schema.')

    def deserialize_eventgrid_events(self, eventgrid_event, **kwargs): # pylint: disable=no-self-use
        # type: (Union[str, dict, bytes], Any) -> Iterable[EventGridEvent]
        """Single event following EventGridEvent schema will be parsed and returned as Deserialized Event.
        :param eventgrid_event: The event to be deserialized.
        :type eventgrid_event: Union[str, dict, bytes]
        :rtype: Iterable[EventGridEvent]

        :raise: :class:`ValueError`, when events do not follow EventGridEvent schema.
        """
        encode = kwargs.pop('encoding', 'utf-8')
        try:
            eventgrid_event = EventGridEvent._from_json(eventgrid_event, encode) # pylint: disable=protected-access
            event_list = []
            for event in eventgrid_event:
                deserialized_event = EventGridEvent.deserialize(event)
                deserialized_event._deserialize_data(deserialized_event, deserialized_event.event_type) # pylint: disable=protected-access
                event_list.append(deserialized_event)
            return event_list
        except Exception as err:
            _LOGGER.error('Your event: %s', eventgrid_event)
            _LOGGER.error(err)
            raise ValueError('Error: cannot deserialize event. Event does not have a valid format. \
                Event must be a string, dict, or bytes following the CloudEvent schema.')
